#! /bin/sh
#
# This script completely configures, compiles and installs the patched tools.
# The download tree must have been patched before doing this.
#
mkdir ../build; cd ../build; mkdir binutils; mkdir gcc;
cd ../scripts; ./launch.binutils; ./launch.gcc;
rm -Rf ../build
cd ../scripts; ./launch.a68k; ./launch.ld-tigcc; ./launch.tigcc; ./launch.tprbuilder; ./launch.patcher; ./launch.envreg
rm -f $TIGCC/bin/parser
