#!/bin/sh
for a in ttbin2hex ttbin2oth ttbin2str ttextract ttstrip ttarchive ttpack ttunpack tthelp ttinfo ttchecksum ttbin2bin ttsplit ttppggen tttiler ttunarchive tthex2bin ttsetname ; # ttdos2ebk ttebkgen ttunebk
do
./buildone $a
done
