#!/bin/sh
for a in ttbin2hex ttbin2oth ttbin2str ttextract ttstrip ttarchive ttpack ttunpack tthelp ttinfo ttchecksum ttbin2bin ttsplit ttppggen tttiler ttunarchive tthex2bin ttsetname ttbin2txt ttdos2ebk ttebkgen ttunebk ;
do
./buildone $a
if [ $? -ne 0 ]; then
exit 1;
fi
done

exit 0
