doorsos::FreeHandles	equ	_ROM_CALL_23B
doorsos::HLock	equ	_ROM_CALL_99
doorsos::HeapAlloc	equ	_ROM_CALL_90
doorsos::HeapAllocESTACK	equ	_ROM_CALL_91
doorsos::HeapAllocHigh	equ	_ROM_CALL_92
doorsos::HeapAllocHighThrow	equ	_ROM_CALL_94
doorsos::HeapAllocPtr	equ	_ROM_CALL_A2
doorsos::HeapAllocThrow	equ	_ROM_CALL_93
doorsos::HeapAvail	equ	_ROM_CALL_8F
doorsos::HeapCompress	equ	_ROM_CALL_95
doorsos::HeapDeref	equ	_ROM_CALL_96
doorsos::HeapEnd	equ	_ROM_CALL_A1
doorsos::HeapFree	equ	_ROM_CALL_97
doorsos::HeapFreeIndir	equ	_ROM_CALL_98
doorsos::HeapFreePtr	equ	_ROM_CALL_A3
doorsos::HeapGetHandle	equ	_ROM_CALL_239
doorsos::HeapGetLock	equ	_ROM_CALL_9B
doorsos::HeapLock	equ	_ROM_CALL_9A
doorsos::HeapMax	equ	_ROM_CALL_9C
doorsos::HeapMoveHigh	equ	_ROM_CALL_A0
doorsos::HeapPtrToHandle	equ	_ROM_CALL_23A
doorsos::HeapRealloc	equ	_ROM_CALL_9D
doorsos::HeapShuffle	equ	_ROM_CALL_474
doorsos::HeapSize	equ	_ROM_CALL_9E
doorsos::HeapUnlock	equ	_ROM_CALL_9F
doorsos::HeapWalk	equ	_ROM_CALL_12C
doorsos::free	equ	_ROM_CALL_A3
doorsos::malloc	equ	_ROM_CALL_A2
doorsos::EX_getArg	equ	_ROM_CALL_BE
doorsos::EX_getBCD	equ	_ROM_CALL_BF
doorsos::RemainingArgCnt	equ	_ROM_CALL_3C3
doorsos::cmd_andpic	equ	_ROM_CALL_32A
doorsos::cmd_archive	equ	_ROM_CALL_448
doorsos::cmd_blddata	equ	_ROM_CALL_32B
doorsos::cmd_circle	equ	_ROM_CALL_32C
doorsos::cmd_clrdraw	equ	_ROM_CALL_32D
doorsos::cmd_clrerr	equ	_ROM_CALL_32E
doorsos::cmd_clrgraph	equ	_ROM_CALL_32F
doorsos::cmd_clrhome	equ	_ROM_CALL_330
doorsos::cmd_clrio	equ	_ROM_CALL_331
doorsos::cmd_clrtable	equ	_ROM_CALL_332
doorsos::cmd_copyvar	equ	_ROM_CALL_333
doorsos::cmd_cubicreg	equ	_ROM_CALL_334
doorsos::cmd_custmoff	equ	_ROM_CALL_335
doorsos::cmd_custmon	equ	_ROM_CALL_336
doorsos::cmd_custom	equ	_ROM_CALL_337
doorsos::cmd_cycle	equ	_ROM_CALL_338
doorsos::cmd_cyclepic	equ	_ROM_CALL_339
doorsos::cmd_delfold	equ	_ROM_CALL_33A
doorsos::cmd_delvar	equ	_ROM_CALL_33B
doorsos::cmd_dialog	equ	_ROM_CALL_33C
doorsos::cmd_disp	equ	_ROM_CALL_33D
doorsos::cmd_dispg	equ	_ROM_CALL_33E
doorsos::cmd_disphome	equ	_ROM_CALL_33F
doorsos::cmd_disptbl	equ	_ROM_CALL_340
doorsos::cmd_drawfunc	equ	_ROM_CALL_341
doorsos::cmd_drawinv	equ	_ROM_CALL_342
doorsos::cmd_drawparm	equ	_ROM_CALL_343
doorsos::cmd_drawpol	equ	_ROM_CALL_344
doorsos::cmd_else	equ	_ROM_CALL_345
doorsos::cmd_endfor	equ	_ROM_CALL_346
doorsos::cmd_endloop	equ	_ROM_CALL_347
doorsos::cmd_endtry	equ	_ROM_CALL_348
doorsos::cmd_endwhile	equ	_ROM_CALL_349
doorsos::cmd_exit	equ	_ROM_CALL_34A
doorsos::cmd_expreg	equ	_ROM_CALL_34B
doorsos::cmd_fill	equ	_ROM_CALL_34C
doorsos::cmd_fnoff	equ	_ROM_CALL_34D
doorsos::cmd_fnon	equ	_ROM_CALL_34E
doorsos::cmd_for	equ	_ROM_CALL_34F
doorsos::cmd_get	equ	_ROM_CALL_350
doorsos::cmd_getcalc	equ	_ROM_CALL_351
doorsos::cmd_goto	equ	_ROM_CALL_352
doorsos::cmd_graph	equ	_ROM_CALL_353
doorsos::cmd_if	equ	_ROM_CALL_354
doorsos::cmd_ifthen	equ	_ROM_CALL_355
doorsos::cmd_input	equ	_ROM_CALL_356
doorsos::cmd_inputstr	equ	_ROM_CALL_357
doorsos::cmd_line	equ	_ROM_CALL_358
doorsos::cmd_linehorz	equ	_ROM_CALL_359
doorsos::cmd_linetan	equ	_ROM_CALL_35A
doorsos::cmd_linevert	equ	_ROM_CALL_35B
doorsos::cmd_linreg	equ	_ROM_CALL_35C
doorsos::cmd_lnreg	equ	_ROM_CALL_35D
doorsos::cmd_local	equ	_ROM_CALL_35E
doorsos::cmd_lock	equ	_ROM_CALL_35F
doorsos::cmd_logistic	equ	_ROM_CALL_360
doorsos::cmd_medmed	equ	_ROM_CALL_361
doorsos::cmd_movevar	equ	_ROM_CALL_362
doorsos::cmd_newdata	equ	_ROM_CALL_363
doorsos::cmd_newfold	equ	_ROM_CALL_364
doorsos::cmd_newpic	equ	_ROM_CALL_365
doorsos::cmd_newplot	equ	_ROM_CALL_366
doorsos::cmd_newprob	equ	_ROM_CALL_367
doorsos::cmd_onevar	equ	_ROM_CALL_368
doorsos::cmd_output	equ	_ROM_CALL_369
doorsos::cmd_passerr	equ	_ROM_CALL_36A
doorsos::cmd_pause	equ	_ROM_CALL_36B
doorsos::cmd_plotsoff	equ	_ROM_CALL_36C
doorsos::cmd_plotson	equ	_ROM_CALL_36D
doorsos::cmd_popup	equ	_ROM_CALL_36E
doorsos::cmd_powerreg	equ	_ROM_CALL_36F
doorsos::cmd_printobj	equ	_ROM_CALL_370
doorsos::cmd_prompt	equ	_ROM_CALL_371
doorsos::cmd_ptchg	equ	_ROM_CALL_372
doorsos::cmd_ptoff	equ	_ROM_CALL_373
doorsos::cmd_pton	equ	_ROM_CALL_374
doorsos::cmd_pttext	equ	_ROM_CALL_375
doorsos::cmd_pxlchg	equ	_ROM_CALL_376
doorsos::cmd_pxlcircle	equ	_ROM_CALL_377
doorsos::cmd_pxlhorz	equ	_ROM_CALL_378
doorsos::cmd_pxlline	equ	_ROM_CALL_379
doorsos::cmd_pxloff	equ	_ROM_CALL_37A
doorsos::cmd_pxlon	equ	_ROM_CALL_37B
doorsos::cmd_pxltext	equ	_ROM_CALL_37C
doorsos::cmd_pxlvert	equ	_ROM_CALL_37D
doorsos::cmd_quadreg	equ	_ROM_CALL_37E
doorsos::cmd_quartreg	equ	_ROM_CALL_37F
doorsos::cmd_randseed	equ	_ROM_CALL_380
doorsos::cmd_rclgdb	equ	_ROM_CALL_381
doorsos::cmd_rclpic	equ	_ROM_CALL_382
doorsos::cmd_rename	equ	_ROM_CALL_383
doorsos::cmd_request	equ	_ROM_CALL_384
doorsos::cmd_return	equ	_ROM_CALL_385
doorsos::cmd_rplcpic	equ	_ROM_CALL_386
doorsos::cmd_send	equ	_ROM_CALL_387
doorsos::cmd_sendcalc	equ	_ROM_CALL_388
doorsos::cmd_sendchat	equ	_ROM_CALL_389
doorsos::cmd_shade	equ	_ROM_CALL_38A
doorsos::cmd_showstat	equ	_ROM_CALL_38B
doorsos::cmd_sinreg	equ	_ROM_CALL_38C
doorsos::cmd_slpline	equ	_ROM_CALL_38D
doorsos::cmd_sorta	equ	_ROM_CALL_38E
doorsos::cmd_sortd	equ	_ROM_CALL_38F
doorsos::cmd_stogdb	equ	_ROM_CALL_390
doorsos::cmd_stopic	equ	_ROM_CALL_391
doorsos::cmd_style	equ	_ROM_CALL_392
doorsos::cmd_table	equ	_ROM_CALL_393
doorsos::cmd_text	equ	_ROM_CALL_394
doorsos::cmd_toolbar	equ	_ROM_CALL_395
doorsos::cmd_trace	equ	_ROM_CALL_396
doorsos::cmd_try	equ	_ROM_CALL_397
doorsos::cmd_twovar	equ	_ROM_CALL_398
doorsos::cmd_unarchiv	equ	_ROM_CALL_449
doorsos::cmd_unlock	equ	_ROM_CALL_399
doorsos::cmd_while	equ	_ROM_CALL_39A
doorsos::cmd_xorpic	equ	_ROM_CALL_39B
doorsos::cmd_zoombox	equ	_ROM_CALL_39C
doorsos::cmd_zoomdata	equ	_ROM_CALL_39D
doorsos::cmd_zoomdec	equ	_ROM_CALL_39E
doorsos::cmd_zoomfit	equ	_ROM_CALL_39F
doorsos::cmd_zoomin	equ	_ROM_CALL_3A0
doorsos::cmd_zoomint	equ	_ROM_CALL_3A1
doorsos::cmd_zoomout	equ	_ROM_CALL_3A2
doorsos::cmd_zoomprev	equ	_ROM_CALL_3A3
doorsos::cmd_zoomrcl	equ	_ROM_CALL_3A4
doorsos::cmd_zoomsqr	equ	_ROM_CALL_3A5
doorsos::cmd_zoomstd	equ	_ROM_CALL_3A6
doorsos::cmd_zoomsto	equ	_ROM_CALL_3A7
doorsos::cmd_zoomtrig	equ	_ROM_CALL_3A8
doorsos::did_push_anti_deriv	equ	_ROM_CALL_5B1
doorsos::did_push_series	equ	_ROM_CALL_588
doorsos::push_1st_derivative	equ	_ROM_CALL_5AE
doorsos::push_abs	equ	_ROM_CALL_543
doorsos::push_acos	equ	_ROM_CALL_537
doorsos::push_acosh	equ	_ROM_CALL_53E
doorsos::push_approx	equ	_ROM_CALL_4F7
doorsos::push_asin	equ	_ROM_CALL_536
doorsos::push_asinh	equ	_ROM_CALL_53D
doorsos::push_atan	equ	_ROM_CALL_538
doorsos::push_atanh	equ	_ROM_CALL_53F
doorsos::push_augment	equ	_ROM_CALL_496
doorsos::push_ceiling	equ	_ROM_CALL_54B
doorsos::push_char	equ	_ROM_CALL_497
doorsos::push_coldim	equ	_ROM_CALL_498
doorsos::push_colnorm	equ	_ROM_CALL_499
doorsos::push_comb	equ	_ROM_CALL_542
doorsos::push_comdenom	equ	_ROM_CALL_59B
doorsos::push_conj	equ	_ROM_CALL_547
doorsos::push_cos	equ	_ROM_CALL_533
doorsos::push_cosh	equ	_ROM_CALL_53B
doorsos::push_cross_product	equ	_ROM_CALL_4CE
doorsos::push_csolve	equ	_ROM_CALL_585
doorsos::push_cumsum	equ	_ROM_CALL_49A
doorsos::push_czeros	equ	_ROM_CALL_587
doorsos::push_def_int	equ	_ROM_CALL_5B2
doorsos::push_denominator	equ	_ROM_CALL_55B
doorsos::push_dense_poly_eval	equ	_ROM_CALL_49C
doorsos::push_desolve	equ	_ROM_CALL_58B
doorsos::push_determinant	equ	_ROM_CALL_49D
doorsos::push_diag	equ	_ROM_CALL_49E
doorsos::push_dimension	equ	_ROM_CALL_49F
doorsos::push_div_dif_1c	equ	_ROM_CALL_58D
doorsos::push_div_dif_1f	equ	_ROM_CALL_58C
doorsos::push_dotproduct	equ	_ROM_CALL_4A3
doorsos::push_eigvc	equ	_ROM_CALL_4CF
doorsos::push_eigvl	equ	_ROM_CALL_4D0
doorsos::push_exp	equ	_ROM_CALL_52E
doorsos::push_expand	equ	_ROM_CALL_59A
doorsos::push_extended_prod	equ	_ROM_CALL_5B5
doorsos::push_factor	equ	_ROM_CALL_59C
doorsos::push_floor	equ	_ROM_CALL_54A
doorsos::push_fractional_part	equ	_ROM_CALL_54E
doorsos::push_gcd_numbers	equ	_ROM_CALL_514
doorsos::push_getfold	equ	_ROM_CALL_317
doorsos::push_getkey	equ	_ROM_CALL_316
doorsos::push_getmode	equ	_ROM_CALL_318
doorsos::push_gettype	equ	_ROM_CALL_319
doorsos::push_identity_mat	equ	_ROM_CALL_4A4
doorsos::push_im	equ	_ROM_CALL_546
doorsos::push_instring	equ	_ROM_CALL_31A
doorsos::push_integer_gcd	equ	_ROM_CALL_551
doorsos::push_integer_lcm	equ	_ROM_CALL_552
doorsos::push_integer_part	equ	_ROM_CALL_54D
doorsos::push_integer_quotient	equ	_ROM_CALL_54F
doorsos::push_integer_remainder	equ	_ROM_CALL_550
doorsos::push_is_prime	equ	_ROM_CALL_515
doorsos::push_left	equ	_ROM_CALL_4A5
doorsos::push_lim	equ	_ROM_CALL_5AD
doorsos::push_list_to_mat	equ	_ROM_CALL_4A6
doorsos::push_ln	equ	_ROM_CALL_52F
doorsos::push_log10	equ	_ROM_CALL_530
doorsos::push_mat_to_list	equ	_ROM_CALL_4A8
doorsos::push_matnorm	equ	_ROM_CALL_4A7
doorsos::push_max	equ	_ROM_CALL_58A
doorsos::push_max1	equ	_ROM_CALL_554
doorsos::push_max2	equ	_ROM_CALL_599
doorsos::push_mean	equ	_ROM_CALL_4A9
doorsos::push_median	equ	_ROM_CALL_4AA
doorsos::push_mid	equ	_ROM_CALL_4AB
doorsos::push_min	equ	_ROM_CALL_589
doorsos::push_min1	equ	_ROM_CALL_553
doorsos::push_min2	equ	_ROM_CALL_598
doorsos::push_mod	equ	_ROM_CALL_54C
doorsos::push_mrow	equ	_ROM_CALL_4AC
doorsos::push_mrowadd	equ	_ROM_CALL_4AD
doorsos::push_newlist	equ	_ROM_CALL_4AE
doorsos::push_newmat	equ	_ROM_CALL_4AF
doorsos::push_nint	equ	_ROM_CALL_5B3
doorsos::push_nsolve	equ	_ROM_CALL_583
doorsos::push_nth_derivative	equ	_ROM_CALL_5AF
doorsos::push_numerator	equ	_ROM_CALL_55A
doorsos::push_ord	equ	_ROM_CALL_4B0
doorsos::push_part	equ	_ROM_CALL_31C
doorsos::push_perm	equ	_ROM_CALL_541
doorsos::push_phase	equ	_ROM_CALL_548
doorsos::push_prodlist	equ	_ROM_CALL_4B2
doorsos::push_pttest	equ	_ROM_CALL_31D
doorsos::push_pxltest	equ	_ROM_CALL_31E
doorsos::push_r_cis	equ	_ROM_CALL_549
doorsos::push_rand	equ	_ROM_CALL_31F
doorsos::push_randmat	equ	_ROM_CALL_4B4
doorsos::push_randnorm	equ	_ROM_CALL_4B5
doorsos::push_randpoly	equ	_ROM_CALL_320
doorsos::push_re	equ	_ROM_CALL_545
doorsos::push_rec_to_angle	equ	_ROM_CALL_539
doorsos::push_red_row_ech	equ	_ROM_CALL_4B6
doorsos::push_right	equ	_ROM_CALL_4B7
doorsos::push_rotate	equ	_ROM_CALL_4B8
doorsos::push_round	equ	_ROM_CALL_4B9
doorsos::push_row_echelon	equ	_ROM_CALL_4BE
doorsos::push_rowadd	equ	_ROM_CALL_4BA
doorsos::push_rowdim	equ	_ROM_CALL_4BB
doorsos::push_rownorm	equ	_ROM_CALL_4BC
doorsos::push_rowswap	equ	_ROM_CALL_4BD
doorsos::push_sequence	equ	_ROM_CALL_4BF
doorsos::push_setfold	equ	_ROM_CALL_321
doorsos::push_setgraph	equ	_ROM_CALL_322
doorsos::push_setmode	equ	_ROM_CALL_323
doorsos::push_settable	equ	_ROM_CALL_324
doorsos::push_shift	equ	_ROM_CALL_4C0
doorsos::push_sign	equ	_ROM_CALL_544
doorsos::push_simult	equ	_ROM_CALL_4C1
doorsos::push_sin	equ	_ROM_CALL_532
doorsos::push_sin2	equ	_ROM_CALL_531
doorsos::push_sinh	equ	_ROM_CALL_53A
doorsos::push_solve	equ	_ROM_CALL_584
doorsos::push_sqrt	equ	_ROM_CALL_52B
doorsos::push_stddev	equ	_ROM_CALL_4C3
doorsos::push_str_to_expr	equ	_ROM_CALL_325
doorsos::push_string	equ	_ROM_CALL_326
doorsos::push_submat	equ	_ROM_CALL_4C4
doorsos::push_sumlist	equ	_ROM_CALL_4C5
doorsos::push_summation	equ	_ROM_CALL_5B4
doorsos::push_switch	equ	_ROM_CALL_327
doorsos::push_tan	equ	_ROM_CALL_534
doorsos::push_tanh	equ	_ROM_CALL_53C
doorsos::push_unitv	equ	_ROM_CALL_4C8
doorsos::push_variance	equ	_ROM_CALL_4C9
doorsos::push_when	equ	_ROM_CALL_57D
doorsos::push_zeros	equ	_ROM_CALL_586
doorsos::did_push_to_polar	equ	_ROM_CALL_313
doorsos::push_and	equ	_ROM_CALL_5AB
doorsos::push_arg_minus_1	equ	_ROM_CALL_520
doorsos::push_arg_plus_1	equ	_ROM_CALL_51F
doorsos::push_assignment	equ	_ROM_CALL_4DD
doorsos::push_degrees	equ	_ROM_CALL_314
doorsos::push_difference	equ	_ROM_CALL_51A
doorsos::push_dot_add	equ	_ROM_CALL_4A0
doorsos::push_dot_div	equ	_ROM_CALL_4CD
doorsos::push_dot_exponentiate	equ	_ROM_CALL_596
doorsos::push_dot_mult	equ	_ROM_CALL_4A1
doorsos::push_dot_sub	equ	_ROM_CALL_4A2
doorsos::push_equals	equ	_ROM_CALL_5A3
doorsos::push_exponentiate	equ	_ROM_CALL_595
doorsos::push_factorial	equ	_ROM_CALL_540
doorsos::push_greater_than	equ	_ROM_CALL_5A5
doorsos::push_greater_than_or_equals	equ	_ROM_CALL_5A7
doorsos::push_indir_name	equ	_ROM_CALL_2B2
doorsos::push_less_than	equ	_ROM_CALL_5A6
doorsos::push_less_than_or_equals	equ	_ROM_CALL_5A8
doorsos::push_list_plus	equ	_ROM_CALL_3BD
doorsos::push_list_times	equ	_ROM_CALL_3BE
doorsos::push_matrix_product	equ	_ROM_CALL_3C5
doorsos::push_negate	equ	_ROM_CALL_524
doorsos::push_not	equ	_ROM_CALL_5AA
doorsos::push_not_equals	equ	_ROM_CALL_5A4
doorsos::push_or	equ	_ROM_CALL_5AC
doorsos::push_percent	equ	_ROM_CALL_555
doorsos::push_pow	equ	_ROM_CALL_30F
doorsos::push_product	equ	_ROM_CALL_521
doorsos::push_radians	equ	_ROM_CALL_4B3
doorsos::push_ratio	equ	_ROM_CALL_526
doorsos::push_square	equ	_ROM_CALL_52C
doorsos::push_substitute_no_simplify	equ	_ROM_CALL_489
doorsos::push_substitute_simplify	equ	_ROM_CALL_5B9
doorsos::push_substitute_using_such_that	equ	_ROM_CALL_5BE
doorsos::push_sum	equ	_ROM_CALL_594
doorsos::push_to_cylin	equ	_ROM_CALL_328
doorsos::push_to_sphere	equ	_ROM_CALL_329
doorsos::CertificateMemory	equ	_ROM_CALL_43E
doorsos::ceof	equ	_ROM_CALL_128
doorsos::cfindfield	equ	_ROM_CALL_12A
doorsos::cgetc	equ	_ROM_CALL_12B
doorsos::cgetcertrevno	equ	_ROM_CALL_2A0
doorsos::cgetflen	equ	_ROM_CALL_12D
doorsos::cgetfnl	equ	_ROM_CALL_12E
doorsos::cgetnl	equ	_ROM_CALL_12F
doorsos::cgetns	equ	_ROM_CALL_130
doorsos::cgetsn	equ	_ROM_CALL_2A1
doorsos::copen	equ	_ROM_CALL_132
doorsos::copensub	equ	_ROM_CALL_133
doorsos::cputhdr	equ	_ROM_CALL_134
doorsos::cputnl	equ	_ROM_CALL_135
doorsos::cputns	equ	_ROM_CALL_136
doorsos::cread	equ	_ROM_CALL_137
doorsos::ctell	equ	_ROM_CALL_138
doorsos::cwrite	equ	_ROM_CALL_139
doorsos::Dialog	equ	_ROM_CALL_30
doorsos::DialogAdd	equ	_ROM_CALL_33
doorsos::DialogDo	equ	_ROM_CALL_32
doorsos::DialogNew	equ	_ROM_CALL_34
doorsos::DlgMessage	equ	_ROM_CALL_1B4
doorsos::VarNew	equ	_ROM_CALL_28E
doorsos::VarOpen	equ	_ROM_CALL_28C
doorsos::VarSaveAs	equ	_ROM_CALL_28D
doorsos::ERD_dialog	equ	_ROM_CALL_151
doorsos::ERD_process	equ	_ROM_CALL_152
doorsos::ER_catch	equ	_ROM_CALL_154
doorsos::ER_success	equ	_ROM_CALL_155
doorsos::ER_throwVar	equ	_ROM_CALL_153
doorsos::find_error_message	equ	_ROM_CALL_2C1
doorsos::ARb_int_count	equ	_ROM_CALL_5C3
doorsos::ARb_real_count	equ	_ROM_CALL_5C2
doorsos::GetValue	equ	_ROM_CALL_2CB
doorsos::HToESI	equ	_ROM_CALL_247
doorsos::NG_RPNToText	equ	_ROM_CALL_25B
doorsos::NG_approxESI	equ	_ROM_CALL_25C
doorsos::NG_execute	equ	_ROM_CALL_25D
doorsos::NG_graphESI	equ	_ROM_CALL_25E
doorsos::NG_rationalESI	equ	_ROM_CALL_25F
doorsos::NG_tokenize	equ	_ROM_CALL_260
doorsos::Parms2D	equ	_ROM_CALL_4D
doorsos::Parse1DExpr	equ	_ROM_CALL_4F
doorsos::Parse2DExpr	equ	_ROM_CALL_4A
doorsos::Parse2DMultiExpr	equ	_ROM_CALL_4B
doorsos::Print2DExpr	equ	_ROM_CALL_4C
doorsos::TokenizeSymName	equ	_ROM_CALL_80
doorsos::add1_to_top	equ	_ROM_CALL_51D
doorsos::add_to_top	equ	_ROM_CALL_518
doorsos::all_tail	equ	_ROM_CALL_3B5
doorsos::and_onto_top	equ	_ROM_CALL_579
doorsos::any_tail	equ	_ROM_CALL_3B6
doorsos::are_expressions_identical	equ	_ROM_CALL_2BF
doorsos::bottom_estack	equ	_ROM_CALL_432
doorsos::can_be_approxed	equ	_ROM_CALL_2F5
doorsos::check_estack_size	equ	_ROM_CALL_2C2
doorsos::compare_Floats	equ	_ROM_CALL_2F7
doorsos::compare_complex_magnitudes	equ	_ROM_CALL_2F6
doorsos::compare_expressions	equ	_ROM_CALL_2C0
doorsos::delete_between	equ	_ROM_CALL_2C3
doorsos::delete_expression	equ	_ROM_CALL_2C5
doorsos::deleted_between	equ	_ROM_CALL_2C4
doorsos::deleted_expression	equ	_ROM_CALL_2C6
doorsos::did_push_cnvrt_Float_to_integer	equ	_ROM_CALL_2F8
doorsos::display_statements	equ	_ROM_CALL_4E
doorsos::estack_number_to_Float	equ	_ROM_CALL_2F9
doorsos::estack_to_short	equ	_ROM_CALL_2C7
doorsos::estack_to_ushort	equ	_ROM_CALL_2C8
doorsos::factor_base_index	equ	_ROM_CALL_2C9
doorsos::factor_exponent_index	equ	_ROM_CALL_2CA
doorsos::gcd_exact_whole_Floats	equ	_ROM_CALL_2FC
doorsos::get_key_ptr	equ	_ROM_CALL_2B7
doorsos::im_index	equ	_ROM_CALL_2CC
doorsos::index_below_display_expression_aux	equ	_ROM_CALL_2B6
doorsos::index_main_var	equ	_ROM_CALL_2CF
doorsos::index_numeric_term	equ	_ROM_CALL_2CD
doorsos::index_of_lead_base_of_lead_term	equ	_ROM_CALL_2CE
doorsos::integer_non_unknown	equ	_ROM_CALL_50C
doorsos::is0	equ	_ROM_CALL_269
doorsos::is1	equ	_ROM_CALL_2FD
doorsos::is_Float_exact_whole_number	equ	_ROM_CALL_2FE
doorsos::is_advanced_tag	equ	_ROM_CALL_2D0
doorsos::is_antisymmetric	equ	_ROM_CALL_2D1
doorsos::is_complex0	equ	_ROM_CALL_2D3
doorsos::is_complex_number	equ	_ROM_CALL_2D2
doorsos::is_constant	equ	_ROM_CALL_593
doorsos::is_free_of_tag	equ	_ROM_CALL_2D4
doorsos::is_independent_of	equ	_ROM_CALL_2D5
doorsos::is_independent_of_de_seq_vars	equ	_ROM_CALL_2D6
doorsos::is_independent_of_elements	equ	_ROM_CALL_2D8
doorsos::is_independent_of_tail	equ	_ROM_CALL_2D7
doorsos::is_matrix	equ	_ROM_CALL_3B7
doorsos::is_minus1	equ	_ROM_CALL_508
doorsos::is_monomial	equ	_ROM_CALL_2D9
doorsos::is_monomial_in_kernel	equ	_ROM_CALL_2DA
doorsos::is_narrowly_independent_of	equ	_ROM_CALL_2DB
doorsos::is_negative	equ	_ROM_CALL_575
doorsos::is_never0	equ	_ROM_CALL_577
doorsos::is_nonnegative	equ	_ROM_CALL_574
doorsos::is_nonpositive	equ	_ROM_CALL_576
doorsos::is_polynomial_in_var_or_kern	equ	_ROM_CALL_56B
doorsos::is_positive	equ	_ROM_CALL_573
doorsos::is_square_matrix	equ	_ROM_CALL_3B8
doorsos::is_symmetric	equ	_ROM_CALL_2DC
doorsos::is_tail_independent_of	equ	_ROM_CALL_2DD
doorsos::is_totally_polynomial	equ	_ROM_CALL_56C
doorsos::is_valid_smap_aggregate	equ	_ROM_CALL_3B9
doorsos::is_variable	equ	_ROM_CALL_488
doorsos::is_whole_number	equ	_ROM_CALL_50B
doorsos::last_element_index	equ	_ROM_CALL_3BA
doorsos::lead_base_index	equ	_ROM_CALL_2DE
doorsos::lead_exponent_index	equ	_ROM_CALL_2DF
doorsos::lead_factor_index	equ	_ROM_CALL_2E0
doorsos::lead_term_index	equ	_ROM_CALL_2E1
doorsos::likely_approx_to_complex_number	equ	_ROM_CALL_307
doorsos::likely_approx_to_number	equ	_ROM_CALL_308
doorsos::main_gen_var_index	equ	_ROM_CALL_2E2
doorsos::map_tail	equ	_ROM_CALL_3BB
doorsos::map_tail_Int	equ	_ROM_CALL_3BC
doorsos::map_unary_over_comparison	equ	_ROM_CALL_2E3
doorsos::min_quantum	equ	_ROM_CALL_2E4
doorsos::move_between_to_top	equ	_ROM_CALL_2E5
doorsos::moved_between_to_top	equ	_ROM_CALL_2E6
doorsos::negate_top	equ	_ROM_CALL_525
doorsos::next_expression_index	equ	_ROM_CALL_10A
doorsos::norm1_complex_Float	equ	_ROM_CALL_309
doorsos::numeric_factor_index	equ	_ROM_CALL_2E7
doorsos::push_ANSI_string	equ	_ROM_CALL_48A
doorsos::push_END_TAG	equ	_ROM_CALL_263
doorsos::push_Float	equ	_ROM_CALL_30A
doorsos::push_Float_to_nonneg_int	equ	_ROM_CALL_30B
doorsos::push_Float_to_rat	equ	_ROM_CALL_30C
doorsos::push_LIST_TAG	equ	_ROM_CALL_264
doorsos::push_between	equ	_ROM_CALL_2E8
doorsos::push_cnvrt_integer_if_whole_nmb	equ	_ROM_CALL_30D
doorsos::push_expr2_quantum	equ	_ROM_CALL_2EA
doorsos::push_expr_quantum	equ	_ROM_CALL_2E9
doorsos::push_expression	equ	_ROM_CALL_44D
doorsos::push_internal_simplify	equ	_ROM_CALL_4F8
doorsos::push_long_to_integer	equ	_ROM_CALL_4E3
doorsos::push_next_arb_int	equ	_ROM_CALL_2EB
doorsos::push_next_arb_real	equ	_ROM_CALL_2EC
doorsos::push_next_internal_var	equ	_ROM_CALL_2ED
doorsos::push_offset_array	equ	_ROM_CALL_3C4
doorsos::push_overflow_to_infinity	equ	_ROM_CALL_30E
doorsos::push_parse_text	equ	_ROM_CALL_3CA
doorsos::push_quantum	equ	_ROM_CALL_2EE
doorsos::push_quantum_pair	equ	_ROM_CALL_2EF
doorsos::push_reversed_tail	equ	_ROM_CALL_3BF
doorsos::push_round_Float	equ	_ROM_CALL_310
doorsos::push_simplify	equ	_ROM_CALL_44E
doorsos::push_transpose_aux	equ	_ROM_CALL_3C1
doorsos::push_ulong_to_integer	equ	_ROM_CALL_4E4
doorsos::push_ushort_to_integer	equ	_ROM_CALL_4E5
doorsos::push_zstr	equ	_ROM_CALL_48A
doorsos::re_index	equ	_ROM_CALL_2F2
doorsos::reductum_index	equ	_ROM_CALL_2F0
doorsos::remaining_element_count	equ	_ROM_CALL_3C3
doorsos::remaining_factors_index	equ	_ROM_CALL_2F1
doorsos::reset_control_flags	equ	_ROM_CALL_2F4
doorsos::reset_estack_size	equ	_ROM_CALL_2F3
doorsos::should_and_did_push_approx_arg2	equ	_ROM_CALL_311
doorsos::signum_Float	equ	_ROM_CALL_312
doorsos::subtract1_from_top	equ	_ROM_CALL_51E
doorsos::subtract_from_top	equ	_ROM_CALL_51B
doorsos::top_estack	equ	_ROM_CALL_109
doorsos::ABT_dialog	equ	_ROM_CALL_10D
doorsos::CAT_dialog	equ	_ROM_CALL_125
doorsos::EV_captureEvents	equ	_ROM_CALL_C6
doorsos::EV_centralDispatcher	equ	_ROM_CALL_156
doorsos::EV_clearPasteString	equ	_ROM_CALL_C7
doorsos::EV_defaultHandler	equ	_ROM_CALL_157
doorsos::EV_eventLoop	equ	_ROM_CALL_158
doorsos::EV_getSplitRect	equ	_ROM_CALL_C9
doorsos::EV_getc	equ	_ROM_CALL_C8
doorsos::EV_hook	equ	_ROM_CALL_2A3
doorsos::EV_notifySwitchGraph	equ	_ROM_CALL_CA
doorsos::EV_paintOneWindow	equ	_ROM_CALL_CB
doorsos::EV_paintWindows	equ	_ROM_CALL_CC
doorsos::EV_registerMenu	equ	_ROM_CALL_159
doorsos::EV_restorePainting	equ	_ROM_CALL_CD
doorsos::EV_sendEvent	equ	_ROM_CALL_CE
doorsos::EV_sendEventSide	equ	_ROM_CALL_CF
doorsos::EV_sendString	equ	_ROM_CALL_D0
doorsos::EV_setCmdCheck	equ	_ROM_CALL_D1
doorsos::EV_setCmdState	equ	_ROM_CALL_D2
doorsos::EV_setFKeyState	equ	_ROM_CALL_D3
doorsos::EV_startApp	equ	_ROM_CALL_D4
doorsos::EV_startSide	equ	_ROM_CALL_D5
doorsos::EV_startTask	equ	_ROM_CALL_D6
doorsos::EV_suspendPainting	equ	_ROM_CALL_D7
doorsos::EV_switch	equ	_ROM_CALL_D8
doorsos::MO_currentOptions	equ	_ROM_CALL_D9
doorsos::MO_defaults	equ	_ROM_CALL_DA
doorsos::MO_digestOptions	equ	_ROM_CALL_DB
doorsos::MO_isMultigraphTask	equ	_ROM_CALL_DC
doorsos::MO_modeDialog	equ	_ROM_CALL_DD
doorsos::MO_notifyModeChange	equ	_ROM_CALL_DE
doorsos::MO_option	equ	_ROM_CALL_447
doorsos::MO_sendQuit	equ	_ROM_CALL_DF
doorsos::ModeSettings	equ	_ROM_CALL_447
doorsos::handleRclKey	equ	_ROM_CALL_14F
doorsos::handleVarLinkKey	equ	_ROM_CALL_129
doorsos::FAccess	equ	_ROM_CALL_3D4
doorsos::FClose	equ	_ROM_CALL_3D5
doorsos::FCreate	equ	_ROM_CALL_3D6
doorsos::FDelete	equ	_ROM_CALL_3D7
doorsos::FEof	equ	_ROM_CALL_3D8
doorsos::FFindFirst	equ	_ROM_CALL_3D9
doorsos::FFindNext	equ	_ROM_CALL_3DA
doorsos::FGetC	equ	_ROM_CALL_3DB
doorsos::FGetPos	equ	_ROM_CALL_3DC
doorsos::FGetSize	equ	_ROM_CALL_3DD
doorsos::FOpen	equ	_ROM_CALL_3DE
doorsos::FPutC	equ	_ROM_CALL_3DF
doorsos::FRead	equ	_ROM_CALL_3E0
doorsos::FSetBufSize	equ	_ROM_CALL_3E2
doorsos::FSetPos	equ	_ROM_CALL_3E1
doorsos::FSetSize	equ	_ROM_CALL_3E3
doorsos::FSetVer	equ	_ROM_CALL_3E4
doorsos::FStatus	equ	_ROM_CALL_3E5
doorsos::FType	equ	_ROM_CALL_3E6
doorsos::FWrite	equ	_ROM_CALL_3E7
doorsos::BatTooLowFlash	equ	_ROM_CALL_434
doorsos::EM_GC	equ	_ROM_CALL_160
doorsos::EM_abandon	equ	_ROM_CALL_15B
doorsos::EM_blockVerifyErase	equ	_ROM_CALL_15D
doorsos::EM_findEmptySlot	equ	_ROM_CALL_15F
doorsos::EM_survey	equ	_ROM_CALL_165
doorsos::EM_write	equ	_ROM_CALL_167
doorsos::FL_addCert	equ	_ROM_CALL_169
doorsos::FL_download	equ	_ROM_CALL_16A
doorsos::FL_getCert	equ	_ROM_CALL_16C
doorsos::FL_getHardwareParmBlock	equ	_ROM_CALL_16B
doorsos::FL_getVerNum	equ	_ROM_CALL_16D
doorsos::FL_write	equ	_ROM_CALL_171
doorsos::FlashMemoryEnd	equ	_ROM_CALL_43D
doorsos::GD_Circle	equ	_ROM_CALL_176
doorsos::GD_Contour	equ	_ROM_CALL_17D
doorsos::GD_Eraser	equ	_ROM_CALL_17A
doorsos::GD_HVLine	equ	_ROM_CALL_178
doorsos::GD_Line	equ	_ROM_CALL_177
doorsos::GD_Pen	equ	_ROM_CALL_179
doorsos::GD_Select	equ	_ROM_CALL_17C
doorsos::GD_Text	equ	_ROM_CALL_17B
doorsos::GR3_paint3d	equ	_ROM_CALL_1FF
doorsos::GR3_xyToWindow	equ	_ROM_CALL_200
doorsos::GZ_Box	equ	_ROM_CALL_22B
doorsos::GZ_Center	equ	_ROM_CALL_22C
doorsos::BitmapGet	equ	_ROM_CALL_185
doorsos::BitmapInit	equ	_ROM_CALL_186
doorsos::BitmapPut	equ	_ROM_CALL_187
doorsos::BitmapSize	equ	_ROM_CALL_188
doorsos::CalcBitmapSize	equ	_ROM_CALL_3EF
doorsos::ClientToScr	equ	_ROM_CALL_42C
doorsos::ClrScr	equ	_ROM_CALL_19E
doorsos::DrawChar	equ	_ROM_CALL_1A4
doorsos::DrawClipChar	equ	_ROM_CALL_191
doorsos::DrawClipEllipse	equ	_ROM_CALL_192
doorsos::DrawClipLine	equ	_ROM_CALL_193
doorsos::DrawClipPix	equ	_ROM_CALL_194
doorsos::DrawClipRect	equ	_ROM_CALL_195
doorsos::DrawFkey	equ	_ROM_CALL_1A5
doorsos::DrawIcon	equ	_ROM_CALL_1A6
doorsos::DrawLine	equ	_ROM_CALL_1A7
doorsos::DrawMultiLines	equ	_ROM_CALL_196
doorsos::DrawPix	equ	_ROM_CALL_1A8
doorsos::DrawStr	equ	_ROM_CALL_1A9
doorsos::DrawStrWidth	equ	_ROM_CALL_197
doorsos::DrawStrWidthP	equ	_ROM_CALL_3EE
doorsos::FillLines2	equ	_ROM_CALL_199
doorsos::FillTriangle	equ	_ROM_CALL_198
doorsos::FontCharWidth	equ	_ROM_CALL_190
doorsos::FontGetSys	equ	_ROM_CALL_18E
doorsos::FontSetSys	equ	_ROM_CALL_18F
doorsos::GetPix	equ	_ROM_CALL_19F
doorsos::LineTo	equ	_ROM_CALL_19C
doorsos::MakeScrRect	equ	_ROM_CALL_42D
doorsos::MoveTo	equ	_ROM_CALL_19D
doorsos::PortRestore	equ	_ROM_CALL_1A3
doorsos::PortSet	equ	_ROM_CALL_1A2
doorsos::QScrRectOverlap	equ	_ROM_CALL_18D
doorsos::RestoreScrState	equ	_ROM_CALL_1A1
doorsos::SaveScrState	equ	_ROM_CALL_1A0
doorsos::ScrRect	equ	_ROM_CALL_2F
doorsos::ScrRectFill	equ	_ROM_CALL_189
doorsos::ScrRectOverlap	equ	_ROM_CALL_18A
doorsos::ScrRectScroll	equ	_ROM_CALL_18B
doorsos::ScrRectShift	equ	_ROM_CALL_18C
doorsos::ScrToHome	equ	_ROM_CALL_2E
doorsos::ScrToWin	equ	_ROM_CALL_2D
doorsos::SetCurAttr	equ	_ROM_CALL_19A
doorsos::SetCurClip	equ	_ROM_CALL_19B
doorsos::CkValidDelta	equ	_ROM_CALL_1C3
doorsos::CptDeltax	equ	_ROM_CALL_1C1
doorsos::CptDeltay	equ	_ROM_CALL_1C2
doorsos::StepCk	equ	_ROM_CALL_1DD
doorsos::gdb_len	equ	_ROM_CALL_1E0
doorsos::gdb_recall	equ	_ROM_CALL_1E2
doorsos::gdb_store	equ	_ROM_CALL_1E1
doorsos::gr_active	equ	_ROM_CALL_10B
doorsos::gr_flags	equ	_ROM_CALL_463
doorsos::gr_other	equ	_ROM_CALL_10C
doorsos::rngLen	equ	_ROM_CALL_1DF
doorsos::HS_chopFIFO	equ	_ROM_CALL_23C
doorsos::HS_countFIFO	equ	_ROM_CALL_23D
doorsos::HS_deleteFIFONode	equ	_ROM_CALL_23E
doorsos::HS_freeAll	equ	_ROM_CALL_23F
doorsos::HS_freeFIFONode	equ	_ROM_CALL_240
doorsos::HS_getAns	equ	_ROM_CALL_241
doorsos::HS_getEntry	equ	_ROM_CALL_242
doorsos::HS_getFIFONode	equ	_ROM_CALL_243
doorsos::HS_newFIFONode	equ	_ROM_CALL_245
doorsos::HS_popEStack	equ	_ROM_CALL_244
doorsos::HS_pushFIFONode	equ	_ROM_CALL_246
doorsos::HomeAlone	equ	_ROM_CALL_506
doorsos::HomeExecute	equ	_ROM_CALL_10E
doorsos::HomePushEStack	equ	_ROM_CALL_10F
doorsos::GKeyDown	equ	_ROM_CALL_17F
doorsos::GKeyFlush	equ	_ROM_CALL_180
doorsos::GKeyIn	equ	_ROM_CALL_17E
doorsos::GetAlphaStatus	equ	_ROM_CALL_164
doorsos::KB_AUTOREPEAT	equ	_ROM_CALL_15C
doorsos::KeyYesOrNo	equ	_ROM_CALL_3EB
doorsos::OSFastArrows	equ	_ROM_CALL_15C
doorsos::OSGetStatKeys	equ	_ROM_CALL_299
doorsos::OSInitBetweenKeyDelay	equ	_ROM_CALL_249
doorsos::OSInitKeyInitDelay	equ	_ROM_CALL_248
doorsos::SetAlphaStatus	equ	_ROM_CALL_163
doorsos::alphaLockOff	equ	_ROM_CALL_482
doorsos::alphaLockOn	equ	_ROM_CALL_481
doorsos::kbhit	equ	_ROM_CALL_52
doorsos::ngetchx	equ	_ROM_CALL_51
doorsos::pushkey	equ	_ROM_CALL_50
doorsos::restoreAlphaLock	equ	_ROM_CALL_483
doorsos::LIO_Get	equ	_ROM_CALL_57
doorsos::LIO_GetMultiple	equ	_ROM_CALL_59
doorsos::LIO_Receive	equ	_ROM_CALL_58
doorsos::LIO_RecvData	equ	_ROM_CALL_5B
doorsos::LIO_Send	equ	_ROM_CALL_56
doorsos::LIO_SendData	equ	_ROM_CALL_5A
doorsos::LIO_SendProduct	equ	_ROM_CALL_253
doorsos::OSCheckSilentLink	equ	_ROM_CALL_24A
doorsos::OSLinkClose	equ	_ROM_CALL_24E
doorsos::OSLinkCmd	equ	_ROM_CALL_24B
doorsos::OSLinkOpen	equ	_ROM_CALL_24D
doorsos::OSLinkReset	equ	_ROM_CALL_24C
doorsos::OSLinkTxQueueActive	equ	_ROM_CALL_252
doorsos::OSLinkTxQueueInquire	equ	_ROM_CALL_251
doorsos::OSReadLinkBlock	equ	_ROM_CALL_24F
doorsos::OSWriteLinkBlock	equ	_ROM_CALL_250
doorsos::getcalc	equ	_ROM_CALL_54
doorsos::sendcalc	equ	_ROM_CALL_55
doorsos::_memset	equ	_ROM_CALL_27B
doorsos::memchr	equ	_ROM_CALL_273
doorsos::memcmp	equ	_ROM_CALL_270
doorsos::memcpy	equ	_ROM_CALL_26A
doorsos::memmove	equ	_ROM_CALL_26B
doorsos::memset	equ	_ROM_CALL_27C
doorsos::memucmp	equ	_ROM_CALL_3CC
doorsos::DynMenuAdd	equ	_ROM_CALL_3F1
doorsos::DynMenuChange	equ	_ROM_CALL_3F0
doorsos::FKeyI_H	equ	_ROM_CALL_592
doorsos::MenuAddIcon	equ	_ROM_CALL_42
doorsos::MenuAddText	equ	_ROM_CALL_41
doorsos::MenuBegin	equ	_ROM_CALL_36
doorsos::MenuCheck	equ	_ROM_CALL_37
doorsos::MenuEnd	equ	_ROM_CALL_38
doorsos::MenuFlags	equ	_ROM_CALL_3F4
doorsos::MenuGetTopRedef	equ	_ROM_CALL_40
doorsos::MenuItemDef	equ	_ROM_CALL_3F3
doorsos::MenuKey	equ	_ROM_CALL_39
doorsos::MenuLoad	equ	_ROM_CALL_3F2
doorsos::MenuNew	equ	_ROM_CALL_43
doorsos::MenuOff	equ	_ROM_CALL_419
doorsos::MenuOn	equ	_ROM_CALL_3A
doorsos::MenuPopup	equ	_ROM_CALL_3B
doorsos::MenuSubStat	equ	_ROM_CALL_3C
doorsos::MenuTopRedef	equ	_ROM_CALL_3F
doorsos::MenuTopSelect	equ	_ROM_CALL_3E
doorsos::MenuTopStat	equ	_ROM_CALL_3D
doorsos::MenuUpdate	equ	_ROM_CALL_49
doorsos::PopupAddText	equ	_ROM_CALL_44
doorsos::PopupBegin	equ	_ROM_CALL_3F5
doorsos::PopupBeginDo	equ	_ROM_CALL_3F6
doorsos::PopupClear	equ	_ROM_CALL_46
doorsos::PopupDo	equ	_ROM_CALL_47
doorsos::PopupNew	equ	_ROM_CALL_45
doorsos::PopupText	equ	_ROM_CALL_48
doorsos::QMenuTopSelect	equ	_ROM_CALL_41A
doorsos::VarCreateFolderPopup	equ	_ROM_CALL_28F
doorsos::MD5Done	equ	_ROM_CALL_257
doorsos::BN_power17Mod	equ	_ROM_CALL_122
doorsos::BN_powerMod	equ	_ROM_CALL_123
doorsos::BN_prodMod	equ	_ROM_CALL_124
doorsos::MD5Final	equ	_ROM_CALL_256
doorsos::MD5Init	equ	_ROM_CALL_254
doorsos::MD5Update	equ	_ROM_CALL_255
doorsos::cdecrypt	equ	_ROM_CALL_127
doorsos::longjmp	equ	_ROM_CALL_267
doorsos::setjmp	equ	_ROM_CALL_266
doorsos::ST_angle	equ	_ROM_CALL_E0
doorsos::ST_batt	equ	_ROM_CALL_E1
doorsos::ST_busy	equ	_ROM_CALL_E2
doorsos::ST_eraseHelp	equ	_ROM_CALL_E3
doorsos::ST_folder	equ	_ROM_CALL_E4
doorsos::ST_graph	equ	_ROM_CALL_E5
doorsos::ST_helpMsg	equ	_ROM_CALL_E6
doorsos::ST_modKey	equ	_ROM_CALL_E7
doorsos::ST_precision	equ	_ROM_CALL_E8
doorsos::ST_progressBar	equ	_ROM_CALL_4D8
doorsos::ST_progressDismiss	equ	_ROM_CALL_4DB
doorsos::ST_progressIncrement	equ	_ROM_CALL_4DA
doorsos::ST_progressUpdate	equ	_ROM_CALL_4D9
doorsos::ST_readOnly	equ	_ROM_CALL_E9
doorsos::ST_refDsp	equ	_ROM_CALL_EB
doorsos::ST_stack	equ	_ROM_CALL_EA
doorsos::sprintf	equ	_ROM_CALL_53
doorsos::cmpstri	equ	_ROM_CALL_16F
doorsos::strcat	equ	_ROM_CALL_26E
doorsos::strchr	equ	_ROM_CALL_274
doorsos::strcmp	equ	_ROM_CALL_271
doorsos::strcpy	equ	_ROM_CALL_26C
doorsos::strcspn	equ	_ROM_CALL_275
doorsos::strerror	equ	_ROM_CALL_27D
doorsos::stricmp	equ	_ROM_CALL_407
doorsos::strlen	equ	_ROM_CALL_27E
doorsos::strncat	equ	_ROM_CALL_26F
doorsos::strncmp	equ	_ROM_CALL_272
doorsos::strncpy	equ	_ROM_CALL_26D
doorsos::strpbrk	equ	_ROM_CALL_276
doorsos::strrchr	equ	_ROM_CALL_277
doorsos::strspn	equ	_ROM_CALL_278
doorsos::strstr	equ	_ROM_CALL_279
doorsos::strtok	equ	_ROM_CALL_27A
doorsos::AB_getGateArrayVersion	equ	_ROM_CALL_15E
doorsos::AB_prodid	equ	_ROM_CALL_29D
doorsos::AB_prodname	equ	_ROM_CALL_29E
doorsos::AB_serno	equ	_ROM_CALL_29F
doorsos::CB_fetchTEXT	equ	_ROM_CALL_C2
doorsos::CB_replaceTEXT	equ	_ROM_CALL_C1
doorsos::CU_cursorState	equ	_ROM_CALL_503
doorsos::CU_restore	equ	_ROM_CALL_C3
doorsos::CU_start	equ	_ROM_CALL_C4
doorsos::CU_stop	equ	_ROM_CALL_C5
doorsos::EX_getBasecodeParmBlock	equ	_ROM_CALL_5DA
doorsos::EX_patch	equ	_ROM_CALL_15A
doorsos::FiftyMsecTick	equ	_ROM_CALL_4FC
doorsos::HelpKeys	equ	_ROM_CALL_181
doorsos::NeedStack	equ	_ROM_CALL_A4
doorsos::OSCheckBreak	equ	_ROM_CALL_EC
doorsos::OSClearBreak	equ	_ROM_CALL_ED
doorsos::OSContrastDn	equ	_ROM_CALL_297
doorsos::OSContrastUp	equ	_ROM_CALL_296
doorsos::OSDisableBreak	equ	_ROM_CALL_EF
doorsos::OSEnableBreak	equ	_ROM_CALL_EE
doorsos::OSFreeTimer	equ	_ROM_CALL_F1
doorsos::OSRegisterTimer	equ	_ROM_CALL_F0
doorsos::OSReset	equ	_ROM_CALL_294
doorsos::OSSetSR	equ	_ROM_CALL_29C
doorsos::OSTimerCurVal	equ	_ROM_CALL_F2
doorsos::OSTimerExpired	equ	_ROM_CALL_F3
doorsos::OSTimerRestart	equ	_ROM_CALL_F4
doorsos::OSdequeue	equ	_ROM_CALL_3AA
doorsos::OSenqueue	equ	_ROM_CALL_3A9
doorsos::OSqclear	equ	_ROM_CALL_3AD
doorsos::OSqhead	equ	_ROM_CALL_3AC
doorsos::OSqinquire	equ	_ROM_CALL_3AB
doorsos::QModeKey	equ	_ROM_CALL_182
doorsos::QSysKey	equ	_ROM_CALL_183
doorsos::ReleaseDate	equ	_ROM_CALL_43F
doorsos::ReleaseVersion	equ	_ROM_CALL_440
doorsos::SumStoChkMem	equ	_ROM_CALL_295
doorsos::WordInList	equ	_ROM_CALL_184
doorsos::XR_stringPtr	equ	_ROM_CALL_293
doorsos::idle	equ	_ROM_CALL_29B
doorsos::off	equ	_ROM_CALL_29A
doorsos::LOC_formatDate	equ	_ROM_CALL_590
doorsos::LOC_getLocalDateFormat	equ	_ROM_CALL_58F
doorsos::LOC_localVersionDate	equ	_ROM_CALL_591
doorsos::OSOnBreak	equ	_ROM_CALL_46E
doorsos::TE_checkSlack	equ	_ROM_CALL_A6
doorsos::TE_close	equ	_ROM_CALL_A5
doorsos::TE_empty	equ	_ROM_CALL_A7
doorsos::TE_focus	equ	_ROM_CALL_A8
doorsos::TE_handleEvent	equ	_ROM_CALL_A9
doorsos::TE_indicateReadOnly	equ	_ROM_CALL_AA
doorsos::TE_isBlank	equ	_ROM_CALL_AB
doorsos::TE_open	equ	_ROM_CALL_AC
doorsos::TE_openFixed	equ	_ROM_CALL_AD
doorsos::TE_pasteText	equ	_ROM_CALL_AE
doorsos::TE_reopen	equ	_ROM_CALL_AF
doorsos::TE_reopenPlain	equ	_ROM_CALL_B0
doorsos::TE_select	equ	_ROM_CALL_B1
doorsos::TE_shrinkWrap	equ	_ROM_CALL_B2
doorsos::TE_unfocus	equ	_ROM_CALL_B3
doorsos::TE_updateCommand	equ	_ROM_CALL_B4
doorsos::acos	equ	_ROM_CALL_F5
doorsos::acosh	equ	_ROM_CALL_288
doorsos::asin	equ	_ROM_CALL_F6
doorsos::asinh	equ	_ROM_CALL_287
doorsos::atan	equ	_ROM_CALL_F7
doorsos::atan2	equ	_ROM_CALL_F8
doorsos::atanh	equ	_ROM_CALL_289
doorsos::cacos	equ	_ROM_CALL_13A
doorsos::cacosh	equ	_ROM_CALL_13D
doorsos::casin	equ	_ROM_CALL_13B
doorsos::casinh	equ	_ROM_CALL_13E
doorsos::catan	equ	_ROM_CALL_13C
doorsos::catanh	equ	_ROM_CALL_13F
doorsos::ccos	equ	_ROM_CALL_140
doorsos::ccosh	equ	_ROM_CALL_143
doorsos::ceil	equ	_ROM_CALL_105
doorsos::cexp	equ	_ROM_CALL_149
doorsos::cln	equ	_ROM_CALL_147
doorsos::clog10	equ	_ROM_CALL_148
doorsos::cos	equ	_ROM_CALL_F9
doorsos::cosh	equ	_ROM_CALL_FC
doorsos::csin	equ	_ROM_CALL_141
doorsos::csinh	equ	_ROM_CALL_144
doorsos::csqrt	equ	_ROM_CALL_146
doorsos::ctan	equ	_ROM_CALL_142
doorsos::ctanh	equ	_ROM_CALL_145
doorsos::exp	equ	_ROM_CALL_FF
doorsos::fabs	equ	_ROM_CALL_106
doorsos::fadd	equ	_ROM_CALL_B6
doorsos::fcmp	equ	_ROM_CALL_BB
doorsos::fdiv	equ	_ROM_CALL_B9
doorsos::float_class	equ	_ROM_CALL_2FA
doorsos::floor	equ	_ROM_CALL_107
doorsos::flt	equ	_ROM_CALL_BD
doorsos::fmod	equ	_ROM_CALL_108
doorsos::fmul	equ	_ROM_CALL_B8
doorsos::fneg	equ	_ROM_CALL_BA
doorsos::fpisanint	equ	_ROM_CALL_172
doorsos::fpisodd	equ	_ROM_CALL_173
doorsos::frexp10	equ	_ROM_CALL_2FB
doorsos::fsub	equ	_ROM_CALL_B7
doorsos::is_float_infinity	equ	_ROM_CALL_2FF
doorsos::is_float_negative_zero	equ	_ROM_CALL_300
doorsos::is_float_positive_zero	equ	_ROM_CALL_301
doorsos::is_float_signed_infinity	equ	_ROM_CALL_302
doorsos::is_float_transfinite	equ	_ROM_CALL_303
doorsos::is_float_unsigned_inf_or_nan	equ	_ROM_CALL_304
doorsos::is_float_unsigned_zero	equ	_ROM_CALL_305
doorsos::is_inf	equ	_ROM_CALL_2FF
doorsos::is_nan	equ	_ROM_CALL_306
doorsos::is_nzero	equ	_ROM_CALL_300
doorsos::is_pzero	equ	_ROM_CALL_301
doorsos::is_sinf	equ	_ROM_CALL_302
doorsos::is_transfinite	equ	_ROM_CALL_303
doorsos::is_uinf_or_nan	equ	_ROM_CALL_304
doorsos::is_uzero	equ	_ROM_CALL_305
doorsos::itrig	equ	_ROM_CALL_28A
doorsos::log	equ	_ROM_CALL_100
doorsos::log10	equ	_ROM_CALL_101
doorsos::modf	equ	_ROM_CALL_102
doorsos::pow	equ	_ROM_CALL_103
doorsos::round12	equ	_ROM_CALL_174
doorsos::round12_err	equ	_ROM_CALL_227
doorsos::round14	equ	_ROM_CALL_175
doorsos::sin	equ	_ROM_CALL_FA
doorsos::sincos	equ	_ROM_CALL_286
doorsos::sinh	equ	_ROM_CALL_FD
doorsos::sqrt	equ	_ROM_CALL_104
doorsos::tan	equ	_ROM_CALL_FB
doorsos::tanh	equ	_ROM_CALL_FE
doorsos::trig	equ	_ROM_CALL_28B
doorsos::trunc	equ	_ROM_CALL_BC
doorsos::CharNumber	equ	_ROM_CALL_113
doorsos::CheckGraphRef	equ	_ROM_CALL_7D
doorsos::CountGrFunc	equ	_ROM_CALL_1D5
doorsos::CptFuncX	equ	_ROM_CALL_1B9
doorsos::CptIndep	equ	_ROM_CALL_1C9
doorsos::CptLastIndepDE	equ	_ROM_CALL_1EF
doorsos::CreateEmptyList	equ	_ROM_CALL_1E6
doorsos::CustomBegin	equ	_ROM_CALL_14A
doorsos::CustomEnd	equ	_ROM_CALL_14C
doorsos::CustomFree	equ	_ROM_CALL_150
doorsos::CustomMenuItem	equ	_ROM_CALL_14B
doorsos::DataTypeNames	equ	_ROM_CALL_43B
doorsos::EQU_deStatus	equ	_ROM_CALL_16E
doorsos::EQU_getNameInfo	equ	_ROM_CALL_120
doorsos::EQU_select	equ	_ROM_CALL_11E
doorsos::EQU_setStyle	equ	_ROM_CALL_11F
doorsos::ERD_dismissNotice	equ	_ROM_CALL_476
doorsos::ERD_notice	equ	_ROM_CALL_475
doorsos::ER_throwFrame	equ	_ROM_CALL_507
doorsos::EV_appA	equ	_ROM_CALL_452
doorsos::EV_appB	equ	_ROM_CALL_453
doorsos::EV_appSide	equ	_ROM_CALL_458
doorsos::EV_currentApp	equ	_ROM_CALL_45C
doorsos::EV_errorCode	equ	_ROM_CALL_46D
doorsos::EV_flags	equ	_ROM_CALL_5DF
doorsos::EV_quit	equ	_ROM_CALL_48E
doorsos::EV_runningApp	equ	_ROM_CALL_45D
doorsos::FLOATTAB	equ	_ROM_CALL_464
doorsos::FindFunc	equ	_ROM_CALL_1C5
doorsos::FindGrFunc	equ	_ROM_CALL_1C6
doorsos::FirstNonblank	equ	_ROM_CALL_4DE
doorsos::FirstSeqPlot	equ	_ROM_CALL_1D6
doorsos::Float0Index	equ	_ROM_CALL_5D0
doorsos::Float1Index	equ	_ROM_CALL_5D1
doorsos::FloatExp1Index	equ	_ROM_CALL_5D4
doorsos::FloatHalfIndex	equ	_ROM_CALL_5E0
doorsos::FloatMinus1Index	equ	_ROM_CALL_5D2
doorsos::FloatPiIndex	equ	_ROM_CALL_5D3
doorsos::ForceFloat	equ	_ROM_CALL_47D
doorsos::FuncLineFlt	equ	_ROM_CALL_1BF
doorsos::GM_Derivative	equ	_ROM_CALL_1B0
doorsos::GM_DistArc	equ	_ROM_CALL_1B1
doorsos::GM_Inflection	equ	_ROM_CALL_1AD
doorsos::GM_Integrate	equ	_ROM_CALL_1AC
doorsos::GM_Intersect	equ	_ROM_CALL_1AB
doorsos::GM_Math1	equ	_ROM_CALL_1AF
doorsos::GM_Shade	equ	_ROM_CALL_1B2
doorsos::GM_TanLine	equ	_ROM_CALL_1AE
doorsos::GM_Value	equ	_ROM_CALL_1AA
doorsos::GR3_addContours	equ	_ROM_CALL_1FB
doorsos::GR3_freeDB	equ	_ROM_CALL_1FD
doorsos::GR3_handleEvent	equ	_ROM_CALL_1FE
doorsos::GR_Pan	equ	_ROM_CALL_1C4
doorsos::GS_PlotAll	equ	_ROM_CALL_202
doorsos::GS_PlotTrace	equ	_ROM_CALL_201
doorsos::GT_BackupToScr	equ	_ROM_CALL_20C
doorsos::GT_CalcDepVals	equ	_ROM_CALL_20D
doorsos::GT_CenterGraphCursor	equ	_ROM_CALL_20E
doorsos::GT_CursorKey	equ	_ROM_CALL_20F
doorsos::GT_DE_Init_Conds	equ	_ROM_CALL_22A
doorsos::GT_DspFreeTraceCoords	equ	_ROM_CALL_210
doorsos::GT_DspMsg	equ	_ROM_CALL_212
doorsos::GT_DspTraceCoords	equ	_ROM_CALL_211
doorsos::GT_Error	equ	_ROM_CALL_213
doorsos::GT_Format	equ	_ROM_CALL_214
doorsos::GT_FreeTrace	equ	_ROM_CALL_215
doorsos::GT_IncXY	equ	_ROM_CALL_216
doorsos::GT_KeyIn	equ	_ROM_CALL_217
doorsos::GT_Open	equ	_ROM_CALL_21B
doorsos::GT_PrintCursor	equ	_ROM_CALL_229
doorsos::GT_QFloatCursorsInRange	equ	_ROM_CALL_218
doorsos::GT_Regraph	equ	_ROM_CALL_219
doorsos::GT_Regraph_if_neccy	equ	_ROM_CALL_21A
doorsos::GT_SaveAs	equ	_ROM_CALL_21C
doorsos::GT_SelFunc	equ	_ROM_CALL_21D
doorsos::GT_SetCursorXY	equ	_ROM_CALL_21F
doorsos::GT_SetGraphRange	equ	_ROM_CALL_21E
doorsos::GT_Set_Graph_Format	equ	_ROM_CALL_228
doorsos::GT_ShowMarkers	equ	_ROM_CALL_220
doorsos::GT_Trace	equ	_ROM_CALL_221
doorsos::GT_ValidGraphRanges	equ	_ROM_CALL_222
doorsos::GT_WinBound	equ	_ROM_CALL_223
doorsos::GT_WinCursor	equ	_ROM_CALL_224
doorsos::GXcoord	equ	_ROM_CALL_226
doorsos::GYcoord	equ	_ROM_CALL_225
doorsos::GZ_Decimal	equ	_ROM_CALL_22D
doorsos::GZ_Fit	equ	_ROM_CALL_22E
doorsos::GZ_InOut	equ	_ROM_CALL_22F
doorsos::GZ_Integer	equ	_ROM_CALL_230
doorsos::GZ_Previous	equ	_ROM_CALL_231
doorsos::GZ_Recall	equ	_ROM_CALL_232
doorsos::GZ_SetFactors	equ	_ROM_CALL_233
doorsos::GZ_Square	equ	_ROM_CALL_234
doorsos::GZ_Standard	equ	_ROM_CALL_235
doorsos::GZ_Stat	equ	_ROM_CALL_236
doorsos::GZ_Store	equ	_ROM_CALL_237
doorsos::GZ_Trig	equ	_ROM_CALL_238
doorsos::GetStatValue	equ	_ROM_CALL_11B
doorsos::GetSysGraphRef	equ	_ROM_CALL_8A
doorsos::GetTagStr	equ	_ROM_CALL_46C
doorsos::GrAxes	equ	_ROM_CALL_1B7
doorsos::GrClipLine	equ	_ROM_CALL_1C0
doorsos::GrLineFlt	equ	_ROM_CALL_1BE
doorsos::GraphActivate	equ	_ROM_CALL_1FC
doorsos::GraphOrTableCmd	equ	_ROM_CALL_1E4
doorsos::IM_re_tol	equ	_ROM_CALL_5C1
doorsos::InitDEAxesRng	equ	_ROM_CALL_1E9
doorsos::InitDEMem	equ	_ROM_CALL_1EA
doorsos::InitTimeSeq	equ	_ROM_CALL_1D9
doorsos::Integer0Index	equ	_ROM_CALL_5CD
doorsos::Integer1Index	equ	_ROM_CALL_5CE
doorsos::Integer2Index	equ	_ROM_CALL_5E1
doorsos::IntegerMinus1Index	equ	_ROM_CALL_5CF
doorsos::LIO_SendIdList	equ	_ROM_CALL_3D0
doorsos::LoadSymFromFindHandle	equ	_ROM_CALL_281
doorsos::NG_cleanup_graph_fun	equ	_ROM_CALL_262
doorsos::NG_control	equ	_ROM_CALL_466
doorsos::NG_setup_graph_fun	equ	_ROM_CALL_261
doorsos::NG_such_that_index	equ	_ROM_CALL_5D7
doorsos::OO_AppNameToACB	equ	_ROM_CALL_406
doorsos::OO_CondGetAttr	equ	_ROM_CALL_3FA
doorsos::OO_Deref	equ	_ROM_CALL_3FB
doorsos::OO_Destroy	equ	_ROM_CALL_423
doorsos::OO_DestroyAll	equ	_ROM_CALL_4F5
doorsos::OO_GetAppAttr	equ	_ROM_CALL_3FC
doorsos::OO_GetAttr	equ	_ROM_CALL_3FD
doorsos::OO_HasAttr	equ	_ROM_CALL_3FE
doorsos::OO_InstallAppHook	equ	_ROM_CALL_490
doorsos::OO_InstallAppHookByName	equ	_ROM_CALL_492
doorsos::OO_InstallSystemHook	equ	_ROM_CALL_404
doorsos::OO_New	equ	_ROM_CALL_3FF
doorsos::OO_NextACB	equ	_ROM_CALL_402
doorsos::OO_PrevACB	equ	_ROM_CALL_403
doorsos::OO_SetAppAttr	equ	_ROM_CALL_400
doorsos::OO_SetAttr	equ	_ROM_CALL_401
doorsos::OO_SuperFrame	equ	_ROM_CALL_48F
doorsos::OO_UninstallAppHook	equ	_ROM_CALL_491
doorsos::OO_UninstallAppHookByName	equ	_ROM_CALL_493
doorsos::OO_UninstallSystemHook	equ	_ROM_CALL_405
doorsos::OO_appGetPublicStorage	equ	_ROM_CALL_425
doorsos::OO_appIsMarkedDelete	equ	_ROM_CALL_426
doorsos::OO_appMarkDelete	equ	_ROM_CALL_427
doorsos::OO_appSetPublicStorage	equ	_ROM_CALL_429
doorsos::OO_firstACB	equ	_ROM_CALL_451
doorsos::OSCheckLinkOpen	equ	_ROM_CALL_5E3
doorsos::OSKeyScan	equ	_ROM_CALL_298
doorsos::OSModKeyStatus	equ	_ROM_CALL_431
doorsos::ParseSymName	equ	_ROM_CALL_78
doorsos::PlotDel	equ	_ROM_CALL_203
doorsos::PlotDup	equ	_ROM_CALL_207
doorsos::PlotGet	equ	_ROM_CALL_205
doorsos::PlotInit	equ	_ROM_CALL_206
doorsos::PlotLookup	equ	_ROM_CALL_209
doorsos::PlotPut	equ	_ROM_CALL_204
doorsos::PlotSize	equ	_ROM_CALL_208
doorsos::QActivePlots	equ	_ROM_CALL_20A
doorsos::QPlotActive	equ	_ROM_CALL_20B
doorsos::QSkipGraphErr	equ	_ROM_CALL_1E7
doorsos::QstatRcl	equ	_ROM_CALL_40B
doorsos::RAtionalize_tol	equ	_ROM_CALL_5C0
doorsos::RM_Type	equ	_ROM_CALL_5DC
doorsos::ReallocExprStruct	equ	_ROM_CALL_14D
doorsos::Regraph	equ	_ROM_CALL_1B6
doorsos::SP_Define	equ	_ROM_CALL_110
doorsos::ST_flags	equ	_ROM_CALL_443
doorsos::ScrRectDivide	equ	_ROM_CALL_28
doorsos::SearchExprStruct	equ	_ROM_CALL_14E
doorsos::SetGraphMode	equ	_ROM_CALL_1B5
doorsos::TIOS_EV_getAppID	equ	_ROM_CALL_454
doorsos::TIOS_abs	equ	_ROM_CALL_5BA
doorsos::TIOS_div	equ	_ROM_CALL_5BB
doorsos::TIOS_labs	equ	_ROM_CALL_5BC
doorsos::TIOS_ldiv	equ	_ROM_CALL_5BD
doorsos::TIOS_strtol	equ	_ROM_CALL_4FF
doorsos::TokenizeName	equ	_ROM_CALL_3E9
doorsos::UpdateWindows	equ	_ROM_CALL_2B
doorsos::ValidateStore	equ	_ROM_CALL_8D
doorsos::VarGraphRefBitsClear	equ	_ROM_CALL_268
doorsos::VarOptList	equ	_ROM_CALL_444
doorsos::VarSaveTitle	equ	_ROM_CALL_290
doorsos::VarStoreLink	equ	_ROM_CALL_87
doorsos::XCvtFtoP	equ	_ROM_CALL_1BD
doorsos::XCvtPtoF	equ	_ROM_CALL_1BA
doorsos::YCvtFtoP	equ	_ROM_CALL_1BC
doorsos::YCvtFtoWin	equ	_ROM_CALL_1B3
doorsos::YCvtPtoF	equ	_ROM_CALL_1BB
doorsos::_bcd_math	equ	_ROM_CALL_B5
doorsos::_ds16u16	equ	_ROM_CALL_2A4
doorsos::_ds32s32	equ	_ROM_CALL_2A8
doorsos::_du16u16	equ	_ROM_CALL_2A6
doorsos::_du32u32	equ	_ROM_CALL_2AA
doorsos::_ms16u16	equ	_ROM_CALL_2A5
doorsos::_ms32s32	equ	_ROM_CALL_2A9
doorsos::_mu16u16	equ	_ROM_CALL_2A7
doorsos::_mu32u32	equ	_ROM_CALL_2AB
doorsos::are_units_consistent	equ	_ROM_CALL_40F
doorsos::assign_between	equ	_ROM_CALL_2AC
doorsos::ck_valid_float	equ	_ROM_CALL_1E5
doorsos::cleanup_de_mem	equ	_ROM_CALL_1EC
doorsos::cleanup_seq_mem	equ	_ROM_CALL_1D7
doorsos::clear_error_context	equ	_ROM_CALL_44C
doorsos::compare_numbers	equ	_ROM_CALL_50D
doorsos::convert_to_TI_92	equ	_ROM_CALL_258
doorsos::cpt_gr_fun	equ	_ROM_CALL_1D1
doorsos::cpt_gr_param	equ	_ROM_CALL_1D2
doorsos::cpt_gr_polar	equ	_ROM_CALL_1D3
doorsos::deStepCk	equ	_ROM_CALL_1F9
doorsos::de_initRes	equ	_ROM_CALL_1F0
doorsos::de_loop	equ	_ROM_CALL_1EB
doorsos::de_rng_no_graph	equ	_ROM_CALL_2A2
doorsos::delete_list_element	equ	_ROM_CALL_2AF
doorsos::did_map_aggregate_arg	equ	_ROM_CALL_5B8
doorsos::did_push_approx_inflection_point	equ	_ROM_CALL_5B0
doorsos::did_push_divide_units	equ	_ROM_CALL_3AE
doorsos::did_push_lincf	equ	_ROM_CALL_572
doorsos::did_push_var_val	equ	_ROM_CALL_2AD
doorsos::divide_top	equ	_ROM_CALL_527
doorsos::does_push_fetch	equ	_ROM_CALL_2AE
doorsos::dv_create_graph_titles	equ	_ROM_CALL_117
doorsos::dv_findColumn	equ	_ROM_CALL_119
doorsos::errno	equ	_ROM_CALL_5D9
doorsos::estack_max_index	equ	_ROM_CALL_5BF
doorsos::estack_to_float	equ	_ROM_CALL_469
doorsos::execute_graph_func	equ	_ROM_CALL_1D0
doorsos::fix_loop_displacements	equ	_ROM_CALL_170
doorsos::freeIdList	equ	_ROM_CALL_4D6
doorsos::gen_version	equ	_ROM_CALL_259
doorsos::get_lb	equ	_ROM_CALL_516
doorsos::get_list_indices	equ	_ROM_CALL_2B8
doorsos::get_matrix_indices	equ	_ROM_CALL_2B9
doorsos::get_ub	equ	_ROM_CALL_517
doorsos::grFuncName	equ	_ROM_CALL_1C7
doorsos::gr_CptIndepInc	equ	_ROM_CALL_1CA
doorsos::gr_DelFolder	equ	_ROM_CALL_1CC
doorsos::gr_DispLabels	equ	_ROM_CALL_1E3
doorsos::gr_add_fldpic	equ	_ROM_CALL_1F6
doorsos::gr_ck_solvergraph	equ	_ROM_CALL_1FA
doorsos::gr_de_axes_lbl	equ	_ROM_CALL_1F2
doorsos::gr_de_value	equ	_ROM_CALL_1ED
doorsos::gr_del_locals	equ	_ROM_CALL_1CB
doorsos::gr_del_vars_in_folder	equ	_ROM_CALL_1F1
doorsos::gr_delete_fldpic	equ	_ROM_CALL_1F4
doorsos::gr_execute_de	equ	_ROM_CALL_1F3
doorsos::gr_execute_seq	equ	_ROM_CALL_1D4
doorsos::gr_find_de_result	equ	_ROM_CALL_1E8
doorsos::gr_find_el	equ	_ROM_CALL_1F8
doorsos::gr_find_func_index	equ	_ROM_CALL_1EE
doorsos::gr_initCondName	equ	_ROM_CALL_1C8
doorsos::gr_openFolder	equ	_ROM_CALL_1CD
doorsos::gr_remove_fldpic	equ	_ROM_CALL_1F5
doorsos::gr_seq_value	equ	_ROM_CALL_1DC
doorsos::gr_stopic	equ	_ROM_CALL_1F7
doorsos::gr_xres_pixel	equ	_ROM_CALL_1B8
doorsos::hStrAppend	equ	_ROM_CALL_45F
doorsos::has_different_variable	equ	_ROM_CALL_5A0
doorsos::has_unit_base	equ	_ROM_CALL_3AF
doorsos::index_after_match_endtag	equ	_ROM_CALL_2B1
doorsos::index_false	equ	_ROM_CALL_5D6
doorsos::index_if_pushed_binomial_info	equ	_ROM_CALL_5A1
doorsos::index_if_pushed_qquad_info	equ	_ROM_CALL_5A2
doorsos::index_reductum_with_tag_base	equ	_ROM_CALL_59F
doorsos::index_rmng_factor	equ	_ROM_CALL_565
doorsos::index_rmng_fctrs_start_base	equ	_ROM_CALL_564
doorsos::index_rmng_fctrs_start_base_tag	equ	_ROM_CALL_563
doorsos::index_rmng_fctrs_start_fctr_tag	equ	_ROM_CALL_562
doorsos::index_true	equ	_ROM_CALL_5D5
doorsos::init_list_indices	equ	_ROM_CALL_2BA
doorsos::init_matrix_indices	equ	_ROM_CALL_2BB
doorsos::init_unit_system	equ	_ROM_CALL_3B0
doorsos::is_cFloat_agg	equ	_ROM_CALL_465
doorsos::is_complex_Float	equ	_ROM_CALL_48B
doorsos::is_equivalent_to	equ	_ROM_CALL_578
doorsos::is_executable	equ	_ROM_CALL_25A
doorsos::is_neg_lead_numr_coef_re_part	equ	_ROM_CALL_56D
doorsos::is_pathname	equ	_ROM_CALL_3C6
doorsos::is_pos_int_and_eq_quantum	equ	_ROM_CALL_509
doorsos::is_real	equ	_ROM_CALL_5A9
doorsos::is_reciprocal_of_quantum	equ	_ROM_CALL_50A
doorsos::is_term_improper	equ	_ROM_CALL_556
doorsos::is_undefined	equ	_ROM_CALL_5B7
doorsos::is_units_term	equ	_ROM_CALL_3B1
doorsos::lead_conjunct_factor_index	equ	_ROM_CALL_580
doorsos::lead_disjunct_term_index	equ	_ROM_CALL_57E
doorsos::linear_degree	equ	_ROM_CALL_571
doorsos::next_token	equ	_ROM_CALL_3C7
doorsos::next_var_or_kernel_index	equ	_ROM_CALL_56E
doorsos::nonblank	equ	_ROM_CALL_3C8
doorsos::or_onto_top	equ	_ROM_CALL_57B
doorsos::pSymPG	equ	_ROM_CALL_430
doorsos::paint_all_except	equ	_ROM_CALL_11D
doorsos::primary_tag_list	equ	_ROM_CALL_467
doorsos::push0	equ	_ROM_CALL_4E7
doorsos::push1	equ	_ROM_CALL_4E8
doorsos::push_ans_entry	equ	_ROM_CALL_2B0
doorsos::push_auto_units_conversion	equ	_ROM_CALL_3B2
doorsos::push_but_conjunct_factor	equ	_ROM_CALL_582
doorsos::push_but_factor	equ	_ROM_CALL_561
doorsos::push_but_term	equ	_ROM_CALL_56A
doorsos::push_constant_factors	equ	_ROM_CALL_55D
doorsos::push_constant_terms	equ	_ROM_CALL_566
doorsos::push_dependent_factors	equ	_ROM_CALL_55F
doorsos::push_dependent_terms	equ	_ROM_CALL_568
doorsos::push_float_qr_fact	equ	_ROM_CALL_2BC
doorsos::push_format	equ	_ROM_CALL_315
doorsos::push_gcd_then_cofactors	equ	_ROM_CALL_59E
doorsos::push_independent_factors	equ	_ROM_CALL_560
doorsos::push_independent_terms	equ	_ROM_CALL_569
doorsos::push_lu_fact	equ	_ROM_CALL_2BD
doorsos::push_make_proper	equ	_ROM_CALL_557
doorsos::push_minus_recip_of_quantum	equ	_ROM_CALL_510
doorsos::push_mrow_aux	equ	_ROM_CALL_31B
doorsos::push_negate_quantum_as_negint	equ	_ROM_CALL_4F1
doorsos::push_nonconstant_factors	equ	_ROM_CALL_55E
doorsos::push_nonconstant_terms	equ	_ROM_CALL_567
doorsos::push_nonnumeric_factors	equ	_ROM_CALL_55C
doorsos::push_parse_prgm_or_func_text	equ	_ROM_CALL_3C9
doorsos::push_pi	equ	_ROM_CALL_512
doorsos::push_pi_on_quantum	equ	_ROM_CALL_513
doorsos::push_poly_deg_in_var_or_kernel	equ	_ROM_CALL_570
doorsos::push_poly_qr	equ	_ROM_CALL_59D
doorsos::push_quantum_as_nonnegative_int	equ	_ROM_CALL_50E
doorsos::push_quantum_pair_as_pos_frac	equ	_ROM_CALL_511
doorsos::push_reciprocal	equ	_ROM_CALL_597
doorsos::push_reciprocal_of_quantum	equ	_ROM_CALL_50F
doorsos::push_simplify_statements	equ	_ROM_CALL_44F
doorsos::push_sq_matrix_to_whole_number	equ	_ROM_CALL_3C0
doorsos::push_standardize	equ	_ROM_CALL_558
doorsos::push_symbolic_qr_fact	equ	_ROM_CALL_2BE
doorsos::push_trig	equ	_ROM_CALL_535
doorsos::push_unit_system_list	equ	_ROM_CALL_3B3
doorsos::push_user_func	equ	_ROM_CALL_2B3
doorsos::push_var	equ	_ROM_CALL_3CB
doorsos::push_var_kern_tail	equ	_ROM_CALL_56F
doorsos::push_zero_partial_column	equ	_ROM_CALL_3C2
doorsos::raise_to_top	equ	_ROM_CALL_529
doorsos::recall_data_var	equ	_ROM_CALL_112
doorsos::remaining_conjuncts_index	equ	_ROM_CALL_581
doorsos::remaining_disjuncts_index	equ	_ROM_CALL_57F
doorsos::replace_top2_with_and	equ	_ROM_CALL_57A
doorsos::replace_top2_with_difference	equ	_ROM_CALL_51C
doorsos::replace_top2_with_imre	equ	_ROM_CALL_559
doorsos::replace_top2_with_or	equ	_ROM_CALL_57C
doorsos::replace_top2_with_pow	equ	_ROM_CALL_52A
doorsos::replace_top2_with_prod	equ	_ROM_CALL_523
doorsos::replace_top2_with_ratio	equ	_ROM_CALL_528
doorsos::replace_top2_with_sum	equ	_ROM_CALL_519
doorsos::replace_top_with_post_simplified	equ	_ROM_CALL_5B6
doorsos::replace_top_with_reciprocal	equ	_ROM_CALL_52D
doorsos::run_one_seq	equ	_ROM_CALL_1DB
doorsos::seqStepCk	equ	_ROM_CALL_1DE
doorsos::seqWebInit	equ	_ROM_CALL_1DA
doorsos::setup_more_graph_fun	equ	_ROM_CALL_1CE
doorsos::setup_unit_system	equ	_ROM_CALL_3B4
doorsos::sf_width	equ	_ROM_CALL_4D3
doorsos::spike_chk_gr_dirty	equ	_ROM_CALL_11A
doorsos::spike_geo_titles	equ	_ROM_CALL_115
doorsos::spike_in_editor	equ	_ROM_CALL_116
doorsos::spike_optionD	equ	_ROM_CALL_114
doorsos::spike_titles_in_editor	equ	_ROM_CALL_118
doorsos::statEnd	equ	_ROM_CALL_409
doorsos::statFree	equ	_ROM_CALL_40A
doorsos::statStart	equ	_ROM_CALL_408
doorsos::store_data_var	equ	_ROM_CALL_111
doorsos::store_func_def	equ	_ROM_CALL_2B4
doorsos::store_to_subscripted_element	equ	_ROM_CALL_2B5
doorsos::time_loop	equ	_ROM_CALL_1D8
doorsos::times_top	equ	_ROM_CALL_522
doorsos::tokenize_if_TI_92_or_text	equ	_ROM_CALL_265
doorsos::unlock_more_graph_fun	equ	_ROM_CALL_1CF
doorsos::AddSymToFolder	equ	_ROM_CALL_70
doorsos::CheckLinkLockFlag	equ	_ROM_CALL_7F
doorsos::CheckReservedName	equ	_ROM_CALL_8B
doorsos::CheckSysFunc	equ	_ROM_CALL_89
doorsos::ClearUserDef	equ	_ROM_CALL_7E
doorsos::DerefSym	equ	_ROM_CALL_79
doorsos::EM_moveSymFromExtMem	equ	_ROM_CALL_161
doorsos::EM_moveSymToExtMem	equ	_ROM_CALL_162
doorsos::EM_twinSymFromExtMem	equ	_ROM_CALL_166
doorsos::EX_stoBCD	equ	_ROM_CALL_C0
doorsos::FindSymInFolder	equ	_ROM_CALL_71
doorsos::FolderAdd	equ	_ROM_CALL_64
doorsos::FolderAddTemp	equ	_ROM_CALL_73
doorsos::FolderClear	equ	_ROM_CALL_66
doorsos::FolderCount	equ	_ROM_CALL_6B
doorsos::FolderCur	equ	_ROM_CALL_65
doorsos::FolderCurTemp	equ	_ROM_CALL_72
doorsos::FolderDel	equ	_ROM_CALL_66
doorsos::FolderDelAllTemp	equ	_ROM_CALL_75
doorsos::FolderDelTemp	equ	_ROM_CALL_74
doorsos::FolderFind	equ	_ROM_CALL_67
doorsos::FolderGetCur	equ	_ROM_CALL_68
doorsos::FolderOp	equ	_ROM_CALL_69
doorsos::FolderRename	equ	_ROM_CALL_6A
doorsos::GetDataType	equ	_ROM_CALL_435
doorsos::GetFuncPrgmBodyPtr	equ	_ROM_CALL_43A
doorsos::HSYMtoName	equ	_ROM_CALL_7A
doorsos::HSymDel	equ	_ROM_CALL_5F
doorsos::IsMainFolderStr	equ	_ROM_CALL_77
doorsos::MakeHSym	equ	_ROM_CALL_282
doorsos::QSysProtected	equ	_ROM_CALL_88
doorsos::ResetSymFlags	equ	_ROM_CALL_8E
doorsos::SetOK	equ	_ROM_CALL_456
doorsos::SmapTypeStrings	equ	_ROM_CALL_436
doorsos::StrToTokN	equ	_ROM_CALL_7B
doorsos::SymAdd	equ	_ROM_CALL_5C
doorsos::SymAddMain	equ	_ROM_CALL_5D
doorsos::SymAddTwin	equ	_ROM_CALL_27F
doorsos::SymCmp	equ	_ROM_CALL_81
doorsos::SymCpy	equ	_ROM_CALL_82
doorsos::SymCpy0	equ	_ROM_CALL_83
doorsos::SymDel	equ	_ROM_CALL_5E
doorsos::SymDelTwin	equ	_ROM_CALL_280
doorsos::SymFind	equ	_ROM_CALL_60
doorsos::SymFindFirst	equ	_ROM_CALL_6C
doorsos::SymFindFolderName	equ	_ROM_CALL_6F
doorsos::SymFindHome	equ	_ROM_CALL_62
doorsos::SymFindMain	equ	_ROM_CALL_61
doorsos::SymFindNext	equ	_ROM_CALL_6D
doorsos::SymFindPrev	equ	_ROM_CALL_6E
doorsos::SymFindPtr	equ	_ROM_CALL_283
doorsos::SymMove	equ	_ROM_CALL_63
doorsos::SymSysVar	equ	_ROM_CALL_8C
doorsos::TempFolderName	equ	_ROM_CALL_76
doorsos::TokToStrN	equ	_ROM_CALL_7C
doorsos::ValidateSymName	equ	_ROM_CALL_84
doorsos::VarRecall	equ	_ROM_CALL_85
doorsos::VarStore	equ	_ROM_CALL_86
doorsos::checkCurrent	equ	_ROM_CALL_121
doorsos::partial_len	equ	_ROM_CALL_11C
doorsos::DrawStaticButton	equ	_ROM_CALL_35
doorsos::DrawWinBorder	equ	_ROM_CALL_27
doorsos::FirstWindow	equ	_ROM_CALL_0
doorsos::MakeWinRect	equ	_ROM_CALL_2C
doorsos::RectWinToScr	equ	_ROM_CALL_2A
doorsos::RectWinToWin	equ	_ROM_CALL_29
doorsos::SetWinClip	equ	_ROM_CALL_42E
doorsos::WinActivate	equ	_ROM_CALL_1
doorsos::WinAttr	equ	_ROM_CALL_2
doorsos::WinBackground	equ	_ROM_CALL_4
doorsos::WinBackupToScr	equ	_ROM_CALL_3
doorsos::WinBegin	equ	_ROM_CALL_5
doorsos::WinBitmapGet	equ	_ROM_CALL_6
doorsos::WinBitmapPut	equ	_ROM_CALL_7
doorsos::WinBitmapSize	equ	_ROM_CALL_8
doorsos::WinChar	equ	_ROM_CALL_A
doorsos::WinCharXY	equ	_ROM_CALL_9
doorsos::WinClose	equ	_ROM_CALL_B
doorsos::WinClr	equ	_ROM_CALL_C
doorsos::WinDeactivate	equ	_ROM_CALL_D
doorsos::WinDupStat	equ	_ROM_CALL_E
doorsos::WinEllipse	equ	_ROM_CALL_F
doorsos::WinFill	equ	_ROM_CALL_10
doorsos::WinFillLines2	equ	_ROM_CALL_11
doorsos::WinFillTriangle	equ	_ROM_CALL_12
doorsos::WinFont	equ	_ROM_CALL_13
doorsos::WinGetCursor	equ	_ROM_CALL_14
doorsos::WinHeight	equ	_ROM_CALL_292
doorsos::WinHide	equ	_ROM_CALL_15
doorsos::WinHome	equ	_ROM_CALL_16
doorsos::WinLine	equ	_ROM_CALL_17
doorsos::WinLineNC	equ	_ROM_CALL_18
doorsos::WinLineRel	equ	_ROM_CALL_1A
doorsos::WinLineTo	equ	_ROM_CALL_19
doorsos::WinMoveCursor	equ	_ROM_CALL_1B
doorsos::WinMoveRel	equ	_ROM_CALL_1D
doorsos::WinMoveTo	equ	_ROM_CALL_1C
doorsos::WinOpen	equ	_ROM_CALL_1E
doorsos::WinPixGet	equ	_ROM_CALL_1F
doorsos::WinPixSet	equ	_ROM_CALL_20
doorsos::WinReOpen	equ	_ROM_CALL_22
doorsos::WinRect	equ	_ROM_CALL_21
doorsos::WinScrollH	equ	_ROM_CALL_23
doorsos::WinScrollV	equ	_ROM_CALL_24
doorsos::WinStr	equ	_ROM_CALL_25
doorsos::WinStrXY	equ	_ROM_CALL_26
doorsos::WinWidth	equ	_ROM_CALL_291
doorsos::BitmapSizeExt	equ	_ROM_CALL_3ED
doorsos::RectWinToScrExt	equ	_ROM_CALL_415
doorsos::WinBeginPaint	equ	_ROM_CALL_500
doorsos::WinBitmapSizeExt	equ	_ROM_CALL_411
doorsos::WinEndPaint	equ	_ROM_CALL_501
doorsos::WinLineExt	equ	_ROM_CALL_47C
doorsos::WinRemove	equ	_ROM_CALL_414
doorsos::WinStrXYWrap	equ	_ROM_CALL_5DB
doorsos::WinToScr	equ	_ROM_CALL_42F
doorsos::NoCallBack	equ	_ROM_CALL_31
doorsos::caddcert	equ	_ROM_CALL_126
doorsos::cgetvernum	equ	_ROM_CALL_131
doorsos::EM_writeToExtMem	equ	_ROM_CALL_168
doorsos::OSVRegisterTimer	equ	_ROM_CALL_284
doorsos::OSVFreeTimer	equ	_ROM_CALL_285

doorsos::ScreenClear equ _ROM_CALL_19E
doorsos::DrawStrXY equ _ROM_CALL_1A9
doorsos::ArchiveErase equ _ROM_CALL_16A+$10
doorsos::ArchiveWrite equ _ROM_CALL_171
doorsos::bcdadd equ _ROM_CALL_B6
doorsos::bcdcmp equ _ROM_CALL_BB
doorsos::bcddiv equ _ROM_CALL_B9
doorsos::bcdbcd equ _ROM_CALL_BD
doorsos::bcdmul equ _ROM_CALL_B8
doorsos::bcdneg equ _ROM_CALL_BA
doorsos::bcdsub equ _ROM_CALL_B7
doorsos::bcdlong equ _ROM_CALL_BC

doorsos::ST_showHelp	equ	_ROM_CALL_E6
doorsos::DrawTo	equ	_ROM_CALL_19C
doorsos::flush_link	equ	_ROM_CALL_24D
doorsos::receive	equ	_ROM_CALL_24F
doorsos::reset_link	equ	_ROM_CALL_24C
doorsos::transmit	equ	_ROM_CALL_250
doorsos::tx_free	equ	_ROM_CALL_252

doorsos::SymFindFoldername  equ _ROM_CALL_6F
doorsos::MakeHsym  equ _ROM_CALL_282

CALCULATOR		equ	_RAM_CALL_000
HW_VERSION		equ	CALCULATOR+1
LCD_WIDTH		equ	_RAM_CALL_001
LCD_HEIGHT		equ	_RAM_CALL_002
doorsos::ROM_base	equ	_RAM_CALL_003
LCD_LINE_BYTES	equ	_RAM_CALL_004
KEY_LEFT		equ	_RAM_CALL_005
KEY_RIGHT		equ	_RAM_CALL_006
KEY_UP			equ	_RAM_CALL_007
KEY_DOWN		equ	_RAM_CALL_008
KEY_UPRIGHT		equ	_RAM_CALL_009
KEY_DOWNLEFT		equ	_RAM_CALL_00A
KEY_DIAMOND		equ	_RAM_CALL_00B
LCD_SIZE		equ	_RAM_CALL_00C
KEY_SHIFT		equ	_RAM_CALL_00D
doorsos::font_medium	equ	_RAM_CALL_00E
ReturnValue		equ	_RAM_CALL_00F
doorsos::kb_globals	equ	_RAM_CALL_010
doorsos::Heap		equ	_RAM_CALL_011
doorsos::FolderListHandle equ	_RAM_CALL_012
doorsos::MainHandle	equ	_RAM_CALL_013
ROM_VERSION		equ	_RAM_CALL_014

doorsos::font_small	equ	doorsos::font_medium+$800
doorsos::font_large	equ	doorsos::font_medium+$E00

LCD_MEM equ $4c00
doorsos::main_lcd equ LCD_MEM
doorsos::globals equ $4c00
doorsos::OSOnBreak	equ	doorsos::globals+$F02


doorsos::MaxHandles	equ	doorsos::Heap-$16
doorsos::TopHeap   	equ     doorsos::Heap-$C
doorsos::FirstFreeByte	equ	doorsos::Heap-$14

doorsos::kb_vars	equ 	doorsos::kb_globals

KEY_PRESSED_FLAG	equ	doorsos::kb_globals+$1c
GETKEY_CODE		equ	doorsos::kb_globals+$1e

APD_INIT	equ	LCD_MEM+$F10
APD_TIMER	equ	LCD_MEM+$F14
APD_FLAG	equ	LCD_MEM+$F42

doorsos::SYM_ENTRY.name equ 0
doorsos::SYM_ENTRY.flags equ 8
doorsos::SYM_ENTRY.hVal equ $c
doorsos::NULL equ 0
doorsos::H_NULL equ 0
doorsos::RAND_MAX equ $7fff
ACTIVITY_IDLE equ 0
ACTIVITY_BUSY equ 1
ACTIVITY_PAUSED equ 2
doorsos::ER_STOP equ 2
doorsos::ER_DIMENSION equ 230
doorsos::ER_MEMORY equ 670
doorsos::ER_MEMORY_DML equ 810
doorsos::UNDEFINED_TAG equ $2a
doorsos::LIST_TAG equ $d9
doorsos::MATRIX_TAG equ $db
doorsos::END_TAG equ $e5
CALC_TI89 equ 0
CALC_TI92PLUS equ 1

ROM_CALL macro
 move.l ($C8),a4
 add.l #\1*4,a4
 move.l (a4),a4
 jsr (a4)
 endm

EXTRA_RAM_TABLE macro
_extraram:
    xdef _extraram
    endm

EXTRA_RAM_ADDR macro
    dc.w \3
    dc.w \4
\2 equ _extraramaddr@\1
    endm

doorsos::DEREF     macro   ; Dn,An
	lsl.w	#2,\1
        move.l  doorsos::Heap,\2
	move.l	0(\2,\1.w),\2
		endm

SetFont	macro
	move.w	\1,-(a7)
	jsr	doorsos::FontSetSys
	addq.l	#2,a7
		endm

WriteStr	macro	;x,y,col,str
	move.w	\3,-(a7)
	pea	\4(pc)
	move.w	\2,-(a7)
	move.w	\1,-(a7)
	jsr	doorsos::DrawStrXY
	lea	10(a7),a7
                endm

WriteStrA	macro	;x,y,col,An
	move.w	\3,-(a7)
	move.l	\4,-(a7)
	move.w	\2,-(a7)
	move.w	\1,-(a7)
	jsr	doorsos::DrawStrXY
	lea	10(a7),a7
                endm

GetKeyStat	MACRO
		move.w		#$FFFE,d0
		move.b		\1,d1
		rol.w 		d1,d0
		move.w		d0,($600018)
		nop
		nop
		nop
		nop
		move.b		($60001B),d0
		ENDM

DEREF macro
 doorsos::DEREF \1,\2
 endm

handle_ptr macro
 DEREF \1,\2
 endm

doorsos::DEREF_SYM macro
 move.l \1,-(sp)
 jsr doorsos::DerefSym
 add.l #4,sp
 endm


doorsos::ER_throw macro
 dc.w $A000+\1
 endm

inc	MACRO
	addq.\0	#1,\1
	ENDM
INC	MACRO
	addq.\0	#1,\1
	ENDM
dec	MACRO
	subq.\0	#1,\1
	ENDM
DEC	MACRO
	subq.\0	#1,\1
	ENDM


push	MACRO
	move.\0	\1,-(a7)
	ENDM

pop	MACRO
	move.\0	(a7)+,\1
	ENDM
pushm	MACRO
	movem.\0	\1,-(a7)
	ENDM

popm	MACRO
	movem.\0	(a7)+,\1
	ENDM

PUSH	MACRO
	move.\0	\1,-(a7)
	ENDM

POP	MACRO
	move.\0	(a7)+,\1
	ENDM
PUSHM	MACRO
	movem.\0	\1,-(a7)
	ENDM

POPM	MACRO
	movem.\0	(a7)+,\1
	ENDM


_library
_ti89
_ti92plus
