RemainingArgCnt		equ	$3C3
EX_getBCD		equ	$BF
EX_getArg		equ	$BE
cgetflen		equ	$12D
cputns		equ	$136
copen		equ	$132
cgetnl		equ	$12F
cfindfield		equ	$12A
cgetns		equ	$130
cread		equ	$137
cgetsn		equ	$2A1
ceof		equ	$128
cputnl		equ	$135
copensub		equ	$133
ctell		equ	$138
cgetfnl		equ	$12E
cgetc		equ	$12B
cwrite		equ	$139
freeIdList		equ	$4D6
cgetcertrevno		equ	$2A0
CertificateMemory		equ	$43E
cputhdr		equ	$134
push_rownorm		equ	$4BC
push_sign		equ	$544
push_numerator		equ	$55A
push_factor		equ	$59C
push_extended_prod		equ	$5B5
push_setgraph		equ	$322
push_nint		equ	$5B3
push_dimension		equ	$49F
push_atanh		equ	$53F
push_summation		equ	$5B4
push_asin		equ	$536
push_nth_derivative		equ	$5AF
did_push_anti_deriv		equ	$5B1
push_integer_gcd		equ	$551
push_gettype		equ	$319
push_setfold		equ	$321
push_r_cis		equ	$549
push_integer_lcm		equ	$552
push_comdenom		equ	$59B
push_char		equ	$497
push_randnorm		equ	$4B5
push_max		equ	$58A
push_submat		equ	$4C4
push_cosh		equ	$53B
push_polar_vector		equ	$4B1
push_cumsum		equ	$49A
push_czeros		equ	$587
push_coldim		equ	$498
push_cross_product		equ	$4CE
push_mod		equ	$54C
push_randpoly		equ	$320
push_div_dif_1c		equ	$58D
push_median		equ	$4AA
push_pxltest		equ	$31E
push_ceiling		equ	$54B
push_prodlist		equ	$4B2
push_instring		equ	$31A
push_atan		equ	$538
push_switch		equ	$327
push_sin		equ	$532
push_max1		equ	$554
push_ln		equ	$52F
push_1st_derivative		equ	$5AE
push_re		equ	$545
push_approx		equ	$4F7
push_cylin_vector		equ	$49B
push_dense_poly_eval		equ	$49C
push_min1		equ	$553
push_mrowadd		equ	$4AD
push_ord		equ	$4B0
push_acos		equ	$537
push_fractional_part		equ	$54E
push_augment		equ	$496
push_asinh		equ	$53D
push_diag		equ	$49E
push_sin2		equ	$531
push_gcd_numbers		equ	$514
push_spher_vector		equ	$4C2
push_perm		equ	$541
push_part		equ	$31C
push_left		equ	$4A5
push_row_echelon		equ	$4BE
push_sequence		equ	$4BF
push_dotproduct		equ	$4A3
push_matnorm		equ	$4A7
push_rowdim		equ	$4BB
push_sqrt		equ	$52B
push_round		equ	$4B9
push_randmat		equ	$4B4
push_string		equ	$326
push_def_int		equ	$5B2
push_right		equ	$4B7
push_comb		equ	$542
push_mat_to_list		equ	$4A8
did_push_series		equ	$588
push_solve		equ	$584
push_rec_to_angle		equ	$539
push_floor		equ	$54A
push_getmode		equ	$318
push_exp		equ	$52E
push_cos		equ	$533
push_max2		equ	$599
push_shift		equ	$4C0
push_integer_quotient		equ	$54F
push_colnorm		equ	$499
push_list_to_mat		equ	$4A6
push_red_row_ech		equ	$4B6
push_newlist		equ	$4AE
push_mid		equ	$4AB
push_getkey		equ	$316
push_identity_mat		equ	$4A4
push_csolve		equ	$585
push_mean		equ	$4A9
push_acosh		equ	$53E
push_zeros		equ	$586
push_rand		equ	$31F
push_im		equ	$546
push_pttest		equ	$31D
push_rowswap		equ	$4BD
push_simult		equ	$4C1
push_min		equ	$589
push_tan		equ	$534
push_getfold		equ	$317
push_denominator		equ	$55B
push_determinant		equ	$49D
push_integer_part		equ	$54D
push_setmode		equ	$323
push_desolve		equ	$58B
push_newmat		equ	$4AF
push_min2		equ	$598
push_log10		equ	$530
push_sinh		equ	$53A
push_mrow		equ	$4AC
push_unitv		equ	$4C8
push_stddev		equ	$4C3
push_str_to_expr		equ	$325
push_tanh		equ	$53C
push_rotate		equ	$4B8
push_settable		equ	$324
push_rowadd		equ	$4BA
push_when		equ	$57D
push_is_prime		equ	$515
push_sumlist		equ	$4C5
push_variance		equ	$4C9
push_expand		equ	$59A
push_eigvl		equ	$4D0
push_nsolve		equ	$583
push_conj		equ	$547
push_div_dif_1f		equ	$58C
push_phase		equ	$548
push_eigvc		equ	$4CF
push_abs		equ	$543
push_lim		equ	$5AD
push_integer_remainder		equ	$550
ST_flags		equ	$443
push_nonconstant_terms		equ	$567
GT_Set_Graph_Format		equ	$228
IntegerMinus1Index		equ	$5CF
OO_appMarkDelete		equ	$427
cpt_gr_fun		equ	$1D1
GT_SelFunc		equ	$21D
OO_DestroyAll		equ	$4F5
index_if_pushed_qquad_info		equ	$5A2
RM_Type		equ	$5DC
OO_UninstallAppHook		equ	$491
ReallocExprStruct		equ	$14D
gr_del_vars_in_folder		equ	$1F1
NG_cleanup_graph_fun		equ	$262
ForceFloat		equ	$47D
ck_valid_float		equ	$1E5
push_but_factor		equ	$561
EV_currentApp		equ	$45C
XCvtFtoP		equ	$1BD
spike_geo_titles		equ	$115
push_ans_entry		equ	$2B0
DataTypeNames		equ	$43B
gr_CptIndepInc		equ	$1CA
errno		equ	$5D9
YCvtFtoWin		equ	$1B3
push_pi_on_quantum		equ	$513
de_loop		equ	$1EB
is_neg_lead_numr_coef_re_part		equ	$56D
CountGrFunc		equ	$1D5
index_rmng_factor		equ	$565
init_unit_system		equ	$3B0
push_format		equ	$315
index_rmng_fctrs_start_base_tag		equ	$563
OO_SetAppAttr		equ	$400
spike_optionD		equ	$114
LoadSymFromFindHandle		equ	$281
gr_openFolder		equ	$1CD
setup_unit_system		equ	$3B4
GT_DspTraceCoords		equ	$211
gr_initCondName		equ	$1C8
is_units_term		equ	$3B1
push_dependent_factors		equ	$55F
push_mrow_aux		equ	$31B
GrLineFlt		equ	$1BE
OO_InstallAppHook		equ	$490
NG_control		equ	$466
assign_between		equ	$2AC
dv_create_graph_titles		equ	$117
InitDEAxesRng		equ	$1E9
OO_GetAttr		equ	$3FD
did_push_divide_units		equ	$3AE
CustomMenuItem		equ	$14B
NG_setup_graph_fun		equ	$261
TIOS_strtol		equ	$4FF
OO_PrevACB		equ	$403
gr_xres_pixel		equ	$1B8
FLOATTAB		equ	$464
GetStatValue		equ	$11B
cpt_gr_param		equ	$1D2
SP_Define		equ	$110
push_var		equ	$3CB
GZ_Trig		equ	$238
SearchExprStruct		equ	$14E
PlotGet		equ	$205
gr_delete_fldpic		equ	$1F4
GT_CenterGraphCursor		equ	$20E
store_to_subscripted_element		equ	$2B5
spike_chk_gr_dirty		equ	$11A
push_negate_quantum_as_negint		equ	$4F1
OO_NextACB		equ	$402
OO_firstACB		equ	$451
push_unit_system_list		equ	$3B3
FloatPiIndex		equ	$5D3
gr_DispLabels		equ	$1E3
GZ_SetFactors		equ	$233
CustomFree		equ	$150
gr_execute_de		equ	$1F3
OO_Destroy		equ	$423
get_matrix_indices		equ	$2B9
next_var_or_kernel_index		equ	$56E
FirstSeqPlot		equ	$1D6
OO_appGetPublicStorage		equ	$425
_mu16u16		equ	$2A7
TIOS_div		equ	$5BB
GT_KeyIn		equ	$217
GM_Math1		equ	$1AF
GetSysGraphRef		equ	$8A
GT_FreeTrace		equ	$215
ValidateStore		equ	$8D
OO_AppNameToACB		equ	$406
push_but_term		equ	$56A
Float1Index		equ	$5D1
QSkipGraphErr		equ	$1E7
GYcoord		equ	$225
VarSaveTitle		equ	$290
is_undefined		equ	$5B7
GM_Integrate		equ	$1AC
OO_HasAttr		equ	$3FE
gr_stopic		equ	$1F7
store_func_def		equ	$2B4
VarOptList		equ	$444
Integer0Index		equ	$5CD
get_list_indices		equ	$2B8
index_after_match_endtag		equ	$2B1
spike_titles_in_editor		equ	$118
lead_conjunct_factor_index		equ	$580
OO_GetAppAttr		equ	$3FC
GZ_InOut		equ	$22F
cpt_gr_polar		equ	$1D3
push_var_kern_tail		equ	$56F
are_units_consistent		equ	$40F
push_quantum_pair_as_pos_frac		equ	$511
remaining_disjuncts_index		equ	$57F
is_pathname		equ	$3C6
spike_in_editor		equ	$116
GT_Regraph_if_neccy		equ	$21A
init_list_indices		equ	$2BA
OSModKeyStatus		equ	$431
GT_Regraph		equ	$219
CptLastIndepDE		equ	$1EF
execute_graph_func		equ	$1D0
did_push_lincf		equ	$572
push_reciprocal_of_quantum		equ	$50F
push_poly_deg_in_var_or_kernel		equ	$570
gr_find_de_result		equ	$1E8
is_complex_Float		equ	$48B
gr_de_value		equ	$1ED
secondary_tag_list		equ	$5EE
Integer2Index		equ	$5E1
GT_CalcDepVals		equ	$20D
GT_DspMsg		equ	$212
EQU_setStyle		equ	$11F
replace_top_with_post_simplified		equ	$5B6
_bcd_math		equ	$B5
push_dependent_terms		equ	$568
push_make_proper		equ	$557
_mu32u32		equ	$2AB
push0		equ	$4E7
recall_data_var		equ	$112
GraphOrTableCmd		equ	$1E4
GM_Shade		equ	$1B2
FloatMinus1Index		equ	$5D2
GZ_Recall		equ	$232
OO_SuperFrame		equ	$48F
GT_WinBound		equ	$223
push_pi		equ	$512
GXcoord		equ	$226
FloatExp1Index		equ	$5D4
gr_DelFolder		equ	$1CC
_ds32s32		equ	$2A8
primary_tag_list		equ	$467
EV_appB		equ	$453
_du32u32		equ	$2AA
index_reductum_with_tag_base		equ	$59F
QstatRcl		equ	$40B
Regraph		equ	$1B6
NG_such_that_index		equ	$5D7
raise_to_top		equ	$529
did_push_approx_inflection_point		equ	$5B0
PlotDel		equ	$203
push_nonconstant_factors		equ	$55E
VarGraphRefBitsClear		equ	$268
statFree		equ	$40A
GR_Pan		equ	$1C4
CheckGraphRef		equ	$7D
is_cFloat_agg		equ	$465
FindGrFunc		equ	$1C6
GT_DE_Init_Conds		equ	$22A
replace_top2_with_sum		equ	$519
de_rng_no_graph		equ	$2A2
YCvtPtoF		equ	$1BB
GM_TanLine		equ	$1AE
replace_top_with_reciprocal		equ	$52D
push_lu_fact		equ	$2BD
gr_seq_value		equ	$1DC
YCvtFtoP		equ	$1BC
push_independent_terms		equ	$569
GT_PrintCursor		equ	$229
CptIndep		equ	$1C9
GM_Value		equ	$1AA
replace_top2_with_pow		equ	$52A
Integer1Index		equ	$5CE
TIOS_ldiv		equ	$5BD
ScrRectDivide		equ	$28
GZ_Store		equ	$237
index_true		equ	$5D5
push_user_func		equ	$2B3
push_reciprocal		equ	$597
compare_numbers		equ	$50D
push_float_qr_fact		equ	$2BC
init_matrix_indices		equ	$2BB
GM_DistArc		equ	$1B1
divide_top		equ	$527
_ms16u16		equ	$2A5
GetTagStr		equ	$46C
_ms32s32		equ	$2A9
GT_Error		equ	$213
GZ_Standard		equ	$235
deStepCk		equ	$1F9
EQU_select		equ	$11E
FuncLineFlt		equ	$1BF
InitTimeSeq		equ	$1D9
get_lb		equ	$516
does_push_fetch		equ	$2AE
push_auto_units_conversion		equ	$3B2
GT_ValidGraphRanges		equ	$222
PlotLookup		equ	$209
FloatHalfIndex		equ	$5E0
GR3_addContours		equ	$1FB
QPlotActive		equ	$20B
GrClipLine		equ	$1C0
has_unit_base		equ	$3AF
GT_DspFreeTraceCoords		equ	$210
GT_Trace		equ	$221
push1		equ	$4E8
replace_top2_with_ratio		equ	$528
push_poly_qr		equ	$59D
IM_re_tol		equ	$5C1
EV_quit		equ	$48E
push_independent_factors		equ	$560
TokenizeName		equ	$3E9
store_data_var		equ	$111
lead_disjunct_term_index		equ	$57E
index_rmng_fctrs_start_fctr_tag		equ	$562
QActivePlots		equ	$20A
next_token		equ	$3C7
get_ub		equ	$517
GrAxes		equ	$1B7
PlotSize		equ	$208
gr_add_fldpic		equ	$1F6
GZ_Stat		equ	$236
push_simplify_statements		equ	$44F
EV_errorCode		equ	$46D
nonblank		equ	$3C8
push_sq_matrix_to_whole_number		equ	$3C0
EV_appSide		equ	$458
statStart		equ	$408
or_onto_top		equ	$57B
unlock_more_graph_fun		equ	$1CF
gr_ck_solvergraph		equ	$1FA
GT_QFloatCursorsInRange		equ	$218
replace_top2_with_prod		equ	$523
remaining_conjuncts_index		equ	$581
statEnd		equ	$409
tokenize_if_TI_92_or_text		equ	$265
dv_findColumn		equ	$119
_du16u16		equ	$2A6
did_map_aggregate_arg		equ	$5B8
cleanup_seq_mem		equ	$1D7
EV_flags		equ	$5DF
push_minus_recip_of_quantum		equ	$510
GT_ShowMarkers		equ	$220
push_trig		equ	$535
GT_Format		equ	$214
VarStoreLink		equ	$87
gr_del_locals		equ	$1CB
push_but_conjunct_factor		equ	$582
push_constant_terms		equ	$566
paint_all_except		equ	$11D
is_equivalent_to		equ	$578
XCvtPtoF		equ	$1BA
SetGraphMode		equ	$1B5
GM_Derivative		equ	$1B0
GT_BackupToScr		equ	$20C
GraphActivate		equ	$1FC
push_parse_prgm_or_func_text		equ	$3C9
OO_UninstallAppHookByName		equ	$493
_ds16u16		equ	$2A4
push_gcd_then_cofactors		equ	$59E
convert_to_TI_92		equ	$258
GR3_handleEvent		equ	$1FE
OO_Deref		equ	$3FB
seqWebInit		equ	$1DA
gr_find_el		equ	$1F8
linear_degree		equ	$571
PlotDup		equ	$207
GZ_Previous		equ	$231
setup_more_graph_fun		equ	$1CE
gen_version		equ	$259
ParseSymName		equ	$78
has_different_variable		equ	$5A0
EV_appA		equ	$452
OO_UninstallSystemHook		equ	$405
push_standardize		equ	$558
replace_top2_with_and		equ	$57A
EQU_getNameInfo		equ	$120
replace_top2_with_difference		equ	$51C
GZ_Integer		equ	$230
InitDEMem		equ	$1EA
cleanup_de_mem		equ	$1EC
RAtionalize_tol		equ	$5C0
index_rmng_fctrs_start_base		equ	$564
run_one_seq		equ	$1DB
did_push_var_val		equ	$2AD
replace_top2_with_or		equ	$57C
GZ_Decimal		equ	$22D
index_false		equ	$5D6
UpdateWindows		equ	$2B
command_tag_list		equ	$5D8
is_term_improper		equ	$556
GZ_Square		equ	$234
seqStepCk		equ	$1DE
GT_SetCursorXY		equ	$21F
OO_New		equ	$3FF
push_zero_partial_column		equ	$3C2
delete_list_element		equ	$2AF
EQU_deStatus		equ	$16E
OSKeyScan		equ	$298
GT_SaveAs		equ	$21C
clear_error_context		equ	$44C
FindFunc		equ	$1C5
gr_de_axes_lbl		equ	$1F2
EV_runningApp		equ	$45D
ER_throwFrame		equ	$507
CustomBegin		equ	$14A
PlotPut		equ	$204
CptFuncX		equ	$1B9
TIOS_abs		equ	$5BA
gr_execute_seq		equ	$1D4
OO_CondGetAttr		equ	$3FA
OO_appIsMarkedDelete		equ	$426
GT_Open		equ	$21B
GT_SetGraphRange		equ	$21E
GS_PlotTrace		equ	$201
replace_top2_with_imre		equ	$559
is_executable		equ	$25A
GT_WinCursor		equ	$224
OO_appSetPublicStorage		equ	$429
push_constant_factors		equ	$55D
PlotInit		equ	$206
GZ_Fit		equ	$22E
times_top		equ	$522
OO_InstallAppHookByName		equ	$492
CustomEnd		equ	$14C
GM_Intersect		equ	$1AB
OO_SetAttr		equ	$401
GR3_freeDB		equ	$1FD
time_loop		equ	$1D8
gr_remove_fldpic		equ	$1F5
de_initRes		equ	$1F0
OO_InstallSystemHook		equ	$404
gr_find_func_index		equ	$1EE
push_nonnumeric_factors		equ	$55C
push_symbolic_qr_fact		equ	$2BE
GT_CursorKey		equ	$20F
fix_loop_displacements		equ	$170
grFuncName		equ	$1C7
estack_to_float		equ	$469
TIOS_labs		equ	$5BC
pSymPG		equ	$430
GT_IncXY		equ	$216
index_if_pushed_binomial_info		equ	$5A1
GS_PlotAll		equ	$202
Float0Index		equ	$5D0
is_real		equ	$5A9
GM_Inflection		equ	$1AD
push_quantum_as_nonnegative_int		equ	$50E
hStrAppend		equ	$45F
free		equ	$A3
malloc		equ	$A2
HeapDeref		equ	$96
FreeHandles		equ	$23B
HeapAllocESTACK		equ	$91
HeapMax		equ	$9C
HeapAllocThrow		equ	$93
HeapCompress		equ	$95
HeapAllocPtr		equ	$A2
HeapUnlock		equ	$9F
HLock		equ	$99
HeapWalk		equ	$12C
HeapGetLock		equ	$9B
HeapAvail		equ	$8F
HeapFreePtr		equ	$A3
HeapPtrToHandle		equ	$23A
HeapRealloc		equ	$9D
HeapMoveHigh		equ	$A0
HeapShuffle		equ	$474
HeapEnd		equ	$A1
HeapFree		equ	$97
HeapAllocHighThrow		equ	$94
HeapAlloc		equ	$90
HeapGetHandle		equ	$239
HeapSize		equ	$9E
HeapAllocHigh		equ	$92
HeapLock		equ	$9A
HeapFreeIndir		equ	$98
OSGetStatKeys		equ	$299
ngetchx		equ	$51
restoreAlphaLock		equ	$483
GKeyDown		equ	$17F
alphaLockOn		equ	$481
KeyYesOrNo		equ	$3EB
kbhit		equ	$52
SetAlphaStatus		equ	$163
OSFastArrows		equ	$15C
OSInitBetweenKeyDelay		equ	$249
KB_AUTOREPEAT		equ	$15C
GKeyIn		equ	$17E
alphaLockOff		equ	$482
pushkey		equ	$50
OSInitKeyInitDelay		equ	$248
GKeyFlush		equ	$180
GetAlphaStatus		equ	$164
MenuTopStat		equ	$3D
MenuOn		equ	$3A
MenuGetTopRedef		equ	$40
MenuPopup		equ	$3B
PopupDo		equ	$47
VarCreateFolderPopup		equ	$28F
MenuNew		equ	$43
FKeyI_H		equ	$592
MenuAddIcon		equ	$42
PopupText		equ	$48
MenuItemDef		equ	$3F3
DynMenuAdd		equ	$3F1
MenuSubStat		equ	$3C
PopupBeginDo		equ	$3F6
MenuFlags		equ	$3F4
MenuTopSelect		equ	$3E
MenuBegin		equ	$36
MenuOff		equ	$419
MenuEnd		equ	$38
PopupAddText		equ	$44
MenuAddText		equ	$41
MenuTopRedef		equ	$3F
MenuUpdate		equ	$49
QMenuTopSelect		equ	$41A
MenuKey		equ	$39
PopupBegin		equ	$3F5
MenuCheck		equ	$37
MenuLoad		equ	$3F2
DynMenuChange		equ	$3F0
PopupClear		equ	$46
PopupNew		equ	$45
WinStrXY		equ	$26
WinPixSet		equ	$20
WinBegin		equ	$5
WinFillLines2		equ	$11
MakeWinRect		equ	$2C
WinBitmapPut		equ	$7
WinStr		equ	$25
WinBackupToScr		equ	$3
WinDeactivate		equ	$D
RectWinToScrExt		equ	$415
WinMoveCursor		equ	$1B
WinScrollV		equ	$24
WinMoveTo		equ	$1C
WinWidth		equ	$291
WinPixGet		equ	$1F
WinHide		equ	$15
DrawStaticButton		equ	$35
WinClr		equ	$C
SetWinClip		equ	$42E
WinBitmapSize		equ	$8
WinOpen		equ	$1E
FirstWindow		equ	$0
WinReOpen		equ	$22
WinBitmapGet		equ	$6
WinFillTriangle		equ	$12
WinBitmapSizeExt		equ	$411
WinEllipse		equ	$F
WinCharXY		equ	$9
WinMoveRel		equ	$1D
WinStrXYWrap		equ	$5DB
WinGetCursor		equ	$14
WinLineExt		equ	$47C
WinClose		equ	$B
WinChar		equ	$A
WinRect		equ	$21
WinFill		equ	$10
WinFont		equ	$13
WinBackground		equ	$4
WinLineRel		equ	$1A
WinRemove		equ	$414
WinLineTo		equ	$19
BitmapSizeExt		equ	$3ED
WinDupStat		equ	$E
RectWinToScr		equ	$2A
WinHome		equ	$16
WinActivate		equ	$1
WinHeight		equ	$292
WinEndPaint		equ	$501
WinScrollH		equ	$23
WinLineNC		equ	$18
RectWinToWin		equ	$29
DrawWinBorder		equ	$27
WinToScr		equ	$42F
WinBeginPaint		equ	$500
WinLine		equ	$17
WinAttr		equ	$2
HS_getAns		equ	$241
HomeAlone		equ	$506
HS_newFIFONode		equ	$245
HS_chopFIFO		equ	$23C
HS_deleteFIFONode		equ	$23E
HS_pushFIFONode		equ	$246
HomePushEStack		equ	$10F
HS_getFIFONode		equ	$243
HomeExecute		equ	$10E
HS_freeFIFONode		equ	$240
HS_popEStack		equ	$244
HS_countFIFO		equ	$23D
HS_getEntry		equ	$242
HS_freeAll		equ	$23F
FL_addCert		equ	$169
CappedHW1ArchiveMemoryBeginning		equ	$43C
FL_getVerNum		equ	$16D
FL_write		equ	$171
EM_abandon		equ	$15B
EM_findEmptySlot		equ	$15F
FlashMemoryEnd		equ	$43D
FL_getHardwareParmBlock		equ	$16B
EM_blockVerifyErase		equ	$15D
BatTooLowFlash		equ	$434
EM_GC		equ	$160
FL_download		equ	$16A
EM_getArchiveMemoryBeginning		equ	$3CF
FL_getCert		equ	$16C
EM_write		equ	$167
EM_survey		equ	$165
LIO_SendProduct		equ	$253
LIO_RecvData		equ	$5B
OSWriteLinkBlock		equ	$250
OSLinkTxQueueInquire		equ	$251
OSLinkCmd		equ	$24B
LIO_SendData		equ	$5A
LIO_SendIdList		equ	$3D0
OSCheckLinkOpen		equ	$5E3
OSReadLinkBlock		equ	$24F
getcalc		equ	$54
OSCheckSilentLink		equ	$24A
OSLinkClose		equ	$24E
OSLinkReset		equ	$24C
OSLinkTxQueueActive		equ	$252
OSLinkOpen		equ	$24D
LIO_GetMultiple		equ	$59
sendcalc		equ	$55
LIO_Receive		equ	$58
LIO_Send		equ	$56
LIO_Get		equ	$57
sprintf		equ	$53
VarNew		equ	$28E
DlgMessage		equ	$1B4
Dialog		equ	$30
VarSaveAs		equ	$28D
DialogAdd		equ	$33
DialogDo		equ	$32
DialogNew		equ	$34
VarOpen		equ	$28C
gdb_recall		equ	$1E2
gr_flags		equ	$463
StepCk		equ	$1DD
gdb_store		equ	$1E1
gr_active		equ	$10B
gr_other		equ	$10C
CptDeltay		equ	$1C2
rngLen		equ	$1DF
CptDeltax		equ	$1C1
CkValidDelta		equ	$1C3
gdb_len		equ	$1E0
ER_throwVar		equ	$153
ERD_dismissNotice		equ	$476
ER_catch		equ	$154
ERD_dialog		equ	$151
ERD_notice		equ	$475
find_error_message		equ	$2C1
ER_success		equ	$155
ERD_process		equ	$152
longjmp		equ	$267
setjmp		equ	$266
TE_indicateReadOnly		equ	$AA
TE_checkSlack		equ	$A6
TE_select		equ	$B1
TE_isBlank		equ	$AB
TE_pasteText		equ	$AE
TE_focus		equ	$A8
TE_empty		equ	$A7
TE_unfocus		equ	$B3
TE_openFixed		equ	$AD
TE_handleEvent		equ	$A9
TE_reopenPlain		equ	$B0
TE_close		equ	$A5
TE_updateCommand		equ	$B4
TE_shrinkWrap		equ	$B2
TE_open		equ	$AC
TE_reopen		equ	$AF
GD_Circle		equ	$176
GD_Contour		equ	$17D
GZ_Center		equ	$22C
GD_Line		equ	$177
GD_Select		equ	$17C
GR3_xyToWindow		equ	$200
GD_Text		equ	$17B
GZ_Box		equ	$22B
GD_Eraser		equ	$17A
GD_Pen		equ	$179
GR3_paint3d		equ	$1FF
GD_HVLine		equ	$178
push_greater_than_or_equals		equ	$5A7
push_transpose		equ	$4D2
push_dot_sub		equ	$4A2
push_to_sphere		equ	$329
push_ratio		equ	$526
push_sum		equ	$594
push_polar_to_rect_y		equ	$4FA
push_percent		equ	$555
did_push_to_polar		equ	$313
push_dot_add		equ	$4A0
push_or		equ	$5AC
push_square		equ	$52C
push_radians		equ	$4B3
push_and		equ	$5AB
push_list_plus		equ	$3BD
push_exponentiate		equ	$595
push_substitute_simplify		equ	$5B9
push_polar_to_rect_x		equ	$4F9
push_greater_than		equ	$5A5
push_arg_plus_1		equ	$51F
push_substitute_no_simplify		equ	$489
push_matrix_product		equ	$3C5
push_substitute_using_such_that		equ	$5BE
push_negate		equ	$524
push_pow		equ	$30F
push_less_than		equ	$5A6
push_factorial		equ	$540
push_assignment		equ	$4DD
push_dot_mult		equ	$4A1
push_arg_minus_1		equ	$520
push_to_dd		equ	$4C6
push_not_equals		equ	$5A4
push_equals		equ	$5A3
push_to_dms		equ	$4C7
push_degrees		equ	$314
push_not		equ	$5AA
push_indir_name		equ	$2B2
push_dot_div		equ	$4CD
push_product		equ	$521
push_dot_exponentiate		equ	$596
push_list_times		equ	$3BE
push_less_than_or_equals		equ	$5A8
push_difference		equ	$51A
push_to_cylin		equ	$328
ScrRectOverlap		equ	$18A
DrawPix		equ	$1A8
DrawStrWidthP		equ	$3EE
DrawStrWidth		equ	$197
RestoreScrState		equ	$1A1
DrawChar		equ	$1A4
FontGetSys		equ	$18E
DrawStr		equ	$1A9
DrawClipEllipse		equ	$192
ClientToScr		equ	$42C
BitmapSize		equ	$188
SetCurAttr		equ	$19A
ScrRectShift		equ	$18C
PortRestore		equ	$1A3
DrawClipPix		equ	$194
CalcBitmapSize		equ	$3EF
LineTo		equ	$19C
FontSetSys		equ	$18F
BitmapInit		equ	$186
DrawClipChar		equ	$191
FillTriangle		equ	$198
SetCurClip		equ	$19B
SaveScrState		equ	$1A0
ScrToWin		equ	$2D
ScrRectFill		equ	$189
PortSet		equ	$1A2
DrawLine		equ	$1A7
GetPix		equ	$19F
ScrRectScroll		equ	$18B
DrawFkey		equ	$1A5
sf_width		equ	$4D3
MakeScrRect		equ	$42D
MoveTo		equ	$19D
FillLines2		equ	$199
QScrRectOverlap		equ	$18D
DrawClipRect		equ	$195
DrawClipLine		equ	$193
ClrScr		equ	$19E
ScrToHome		equ	$2E
BitmapPut		equ	$187
FontCharWidth		equ	$190
ScrRect		equ	$2F
DrawMultiLines		equ	$196
BitmapGet		equ	$185
DrawIcon		equ	$1A6
strerror		equ	$27D
strncat		equ	$26F
FirstNonblank		equ	$4DE
strstr		equ	$279
strncmp		equ	$272
strcat		equ	$26E
strcspn		equ	$275
CharNumber		equ	$113
strspn		equ	$278
strpbrk		equ	$276
stricmp		equ	$407
strrchr		equ	$277
strcmp		equ	$271
strlen		equ	$27E
strcpy		equ	$26C
strncpy		equ	$26D
cmpstri		equ	$16F
strtok		equ	$27A
strchr		equ	$274
ST_busy		equ	$E2
ST_progressUpdate		equ	$4D9
ST_progressDismiss		equ	$4DB
ST_helpMsg		equ	$E6
ST_angle		equ	$E0
ST_progressBar		equ	$4D8
ST_batt		equ	$E1
ST_modKey		equ	$E7
ST_refDsp		equ	$EB
ST_progressIncrement		equ	$4DA
ST_graph		equ	$E5
ST_precision		equ	$E8
ST_readOnly		equ	$E9
ST_stack		equ	$EA
ST_eraseHelp		equ	$E3
ST_folder		equ	$E4
asin		equ	$F6
cosh		equ	$FC
float_class		equ	$2FA
sincos		equ	$286
fneg		equ	$BA
atan2		equ	$F8
acos		equ	$F5
sinh		equ	$FD
itrig		equ	$28A
is_uinf_or_nan		equ	$304
fabs		equ	$106
fcmp		equ	$BB
ccosh		equ	$143
is_float_signed_infinity		equ	$302
asinh		equ	$287
casinh		equ	$13E
is_nzero		equ	$300
is_float_transfinite		equ	$303
sqrt		equ	$104
trunc		equ	$BC
atan		equ	$F7
cacos		equ	$13A
acosh		equ	$288
atanh		equ	$289
ctan		equ	$142
tan		equ	$FB
is_uzero		equ	$305
is_sinf		equ	$302
cos		equ	$F9
is_float_positive_zero		equ	$301
fpisodd		equ	$173
fpisanint		equ	$172
sin		equ	$FA
is_float_negative_zero		equ	$300
fmod		equ	$108
csin		equ	$141
log		equ	$100
round14		equ	$175
round12_err		equ	$227
round12		equ	$174
pow		equ	$103
ceil		equ	$105
catan		equ	$13C
ctanh		equ	$145
fmul		equ	$B8
log10		equ	$101
is_float_unsigned_inf_or_nan		equ	$304
catanh		equ	$13F
ccos		equ	$140
is_nan		equ	$306
exp		equ	$FF
clog10		equ	$148
casin		equ	$13B
fsub		equ	$B7
is_inf		equ	$2FF
fadd		equ	$B6
cexp		equ	$149
floor		equ	$107
is_float_infinity		equ	$2FF
csinh		equ	$144
modf		equ	$102
cacosh		equ	$13D
is_float_unsigned_zero		equ	$305
tanh		equ	$FE
flt		equ	$BD
trig		equ	$28B
frexp10		equ	$2FB
fdiv		equ	$B9
is_pzero		equ	$301
cln		equ	$147
is_transfinite		equ	$303
csqrt		equ	$146
cmd_delfold		equ	$33A
cmd_newdata		equ	$363
cmd_inputstr		equ	$357
cmd_send		equ	$387
cmd_zoombox		equ	$39C
cmd_if		equ	$354
cmd_graph		equ	$353
cmd_passerr		equ	$36A
cmd_popup		equ	$36E
cmd_lnreg		equ	$35D
cmd_output		equ	$369
cmd_return		equ	$385
cmd_powerreg		equ	$36F
cmd_fnon		equ	$34E
cmd_rclgdb		equ	$381
cmd_linetan		equ	$35A
cmd_shade		equ	$38A
cmd_linevert		equ	$35B
cmd_pxltext		equ	$37C
cmd_zoomrcl		equ	$3A4
cmd_style		equ	$392
cmd_endwhile		equ	$349
cmd_clrdraw		equ	$32D
cmd_pxlon		equ	$37B
cmd_else		equ	$345
cmd_ptoff		equ	$373
cmd_table		equ	$393
cmd_ifthen		equ	$355
cmd_pxlchg		equ	$376
cmd_unarchiv		equ	$449
cmd_zoomprev		equ	$3A3
cmd_text		equ	$394
cmd_lock		equ	$35F
cmd_logistic		equ	$360
cmd_for		equ	$34F
cmd_disphome		equ	$33F
cmd_ptchg		equ	$372
cmd_randseed		equ	$380
cmd_linreg		equ	$35C
cmd_clrio		equ	$331
cmd_unlock		equ	$399
cmd_sendchat		equ	$389
cmd_circle		equ	$32C
cmd_drawparm		equ	$343
cmd_movevar		equ	$362
cmd_onevar		equ	$368
cmd_endtry		equ	$348
cmd_zoomdec		equ	$39E
cmd_sortd		equ	$38F
cmd_pxlcircle		equ	$377
cmd_dispg		equ	$33E
cmd_expreg		equ	$34B
cmd_pxloff		equ	$37A
cmd_dialog		equ	$33C
cmd_rclpic		equ	$382
cmd_clrhome		equ	$330
cmd_xorpic		equ	$39B
cmd_disptbl		equ	$340
cmd_andpic		equ	$32A
cmd_delvar		equ	$33B
cmd_newplot		equ	$366
cmd_archive		equ	$448
cmd_local		equ	$35E
cmd_custmon		equ	$336
cmd_custmoff		equ	$335
cmd_quadreg		equ	$37E
cmd_goto		equ	$352
cmd_pxlline		equ	$379
cmd_cubicreg		equ	$334
cmd_clrgraph		equ	$32F
cmd_slpline		equ	$38D
cmd_newprob		equ	$367
cmd_copyvar		equ	$333
cmd_pxlvert		equ	$37D
cmd_plotsoff		equ	$36C
cmd_zoomin		equ	$3A0
cmd_rplcpic		equ	$386
cmd_while		equ	$39A
cmd_trace		equ	$396
cmd_sendcalc		equ	$388
cmd_fnoff		equ	$34D
cmd_qr_fact		equ	$485
cmd_input		equ	$356
cmd_clrtable		equ	$332
cmd_plotson		equ	$36D
cmd_twovar		equ	$398
cmd_stopic		equ	$391
cmd_endfor		equ	$346
cmd_blddata		equ	$32B
cmd_zoomstd		equ	$3A6
cmd_medmed		equ	$361
cmd_try		equ	$397
cmd_zoomsto		equ	$3A7
cmd_pxlhorz		equ	$378
cmd_zoomsqr		equ	$3A5
cmd_getcalc		equ	$351
cmd_zoomout		equ	$3A2
cmd_fill		equ	$34C
cmd_zoomint		equ	$3A1
cmd_toolbar		equ	$395
cmd_rename		equ	$383
cmd_line		equ	$358
cmd_exit		equ	$34A
cmd_linehorz		equ	$359
cmd_get		equ	$350
cmd_stogdb		equ	$390
cmd_sinreg		equ	$38C
cmd_zoomdata		equ	$39D
cmd_custom		equ	$337
cmd_cycle		equ	$338
cmd_disp		equ	$33D
cmd_pause		equ	$36B
cmd_drawpol		equ	$344
cmd_request		equ	$384
cmd_prompt		equ	$371
cmd_drawinv		equ	$342
cmd_lu_fact		equ	$484
cmd_newpic		equ	$365
cmd_pton		equ	$374
cmd_newfold		equ	$364
cmd_zoomfit		equ	$39F
cmd_zoomtrig		equ	$3A8
cmd_sorta		equ	$38E
cmd_cyclepic		equ	$339
cmd_printobj		equ	$370
cmd_clrerr		equ	$32E
cmd_pttext		equ	$375
cmd_showstat		equ	$38B
cmd_endloop		equ	$347
cmd_quartreg		equ	$37F
cmd_drawfunc		equ	$341
memchr		equ	$273
memset		equ	$27C
_memset		equ	$27B
memmove		equ	$26B
memcmp		equ	$270
memcpy		equ	$26A
memucmp		equ	$3CC
GetValue		equ	$2CB
get_key_ptr		equ	$2B7
push_zstr		equ	$48A
is_minus1		equ	$508
estack_number_to_Float		equ	$2F9
likely_approx_to_complex_number		equ	$307
push_next_arb_real		equ	$2EC
push_expr_quantum		equ	$2E9
is_independent_of_elements		equ	$2D8
integer_non_unknown		equ	$50C
did_push_cnvrt_Float_to_integer		equ	$2F8
is_antisymmetric		equ	$2D1
is_complex0		equ	$2D3
NG_execute		equ	$25D
is_positive		equ	$573
are_expressions_identical		equ	$2BF
top_estack		equ	$109
push_ANSI_string		equ	$48A
min_quantum		equ	$2E4
is_Float_exact_whole_number		equ	$2FE
numeric_factor_index		equ	$2E7
can_be_approxed		equ	$2F5
deleted_between		equ	$2C4
reset_estack_size		equ	$2F3
map_tail_Int		equ	$3BC
TokenizeSymName		equ	$80
is_independent_of_de_seq_vars		equ	$2D6
is_independent_of		equ	$2D5
delete_expression		equ	$2C5
re_index		equ	$2F2
push_expr2_quantum		equ	$2EA
is_matrix		equ	$3B7
factor_base_index		equ	$2C9
push_reversed_tail		equ	$3BF
is_totally_polynomial		equ	$56C
is_nonnegative		equ	$574
push_ulong_to_integer		equ	$4E4
move_between_to_top		equ	$2E5
reset_control_flags		equ	$2F4
push_Float_to_rat		equ	$30C
NG_RPNToText		equ	$25B
check_estack_size		equ	$2C2
ARb_real_count		equ	$5C2
push_transpose_aux		equ	$3C1
is_advanced_tag		equ	$2D0
lead_exponent_index		equ	$2DF
likely_approx_to_number		equ	$308
push_overflow_to_infinity		equ	$30E
map_unary_over_comparison		equ	$2E3
display_statements		equ	$4E
lead_factor_index		equ	$2E0
push_between		equ	$2E8
push_END_TAG		equ	$263
push_round_Float		equ	$310
index_main_var		equ	$2CF
compare_expressions		equ	$2C0
is_monomial		equ	$2D9
and_onto_top		equ	$579
remaining_factors_index		equ	$2F1
Parse1DExpr		equ	$4F
is_monomial_in_kernel		equ	$2DA
main_gen_var_index		equ	$2E2
push_cnvrt_integer_if_whole_nmb		equ	$30D
Parse2DExpr		equ	$4A
NG_graphESI		equ	$25E
is_whole_number		equ	$50B
push_Float_to_nonneg_int		equ	$30B
push_simplify		equ	$44E
Parms2D		equ	$4D
estack_to_ushort		equ	$2C8
push_offset_array		equ	$3C4
index_of_lead_base_of_lead_term		equ	$2CE
push_parse_text		equ	$3CA
Print2DExpr		equ	$4C
im_index		equ	$2CC
remaining_element_count		equ	$3C3
all_tail		equ	$3B5
is_constant		equ	$593
next_expression_index		equ	$10A
index_below_display_expression_aux		equ	$2B6
add_to_top		equ	$518
HToESI		equ	$247
lead_base_index		equ	$2DE
any_tail		equ	$3B6
negate_top		equ	$525
last_element_index		equ	$3BA
is_pos_int_and_eq_quantum		equ	$509
lead_term_index		equ	$2E1
is_free_of_tag		equ	$2D4
subtract_from_top		equ	$51B
CreateEmptyList		equ	$1E6
is_valid_smap_aggregate		equ	$3B9
deleted_expression		equ	$2C6
estack_max_index		equ	$5BF
push_quantum_pair		equ	$2EF
compare_Floats		equ	$2F7
push_LIST_TAG		equ	$264
factor_exponent_index		equ	$2CA
index_numeric_term		equ	$2CD
is_polynomial_in_var_or_kern		equ	$56B
moved_between_to_top		equ	$2E6
map_tail		equ	$3BB
subtract1_from_top		equ	$51E
is_symmetric		equ	$2DC
is1		equ	$2FD
is_negative		equ	$575
is_never0		equ	$577
reductum_index		equ	$2F0
is_narrowly_independent_of		equ	$2DB
bottom_estack		equ	$432
should_and_did_push_approx_arg2		equ	$311
push_long_to_integer		equ	$4E3
is_complex_number		equ	$2D2
push_quantum		equ	$2EE
estack_to_short		equ	$2C7
NG_rationalESI		equ	$25F
delete_between		equ	$2C3
add1_to_top		equ	$51D
norm1_complex_Float		equ	$309
push_ushort_to_integer		equ	$4E5
push_internal_simplify		equ	$4F8
gcd_exact_whole_Floats		equ	$2FC
compare_complex_magnitudes		equ	$2F6
push_next_internal_var		equ	$2ED
is_square_matrix		equ	$3B8
push_Float		equ	$30A
is_nonpositive		equ	$576
push_next_arb_int		equ	$2EB
is_tail_independent_of		equ	$2DD
ARb_int_count		equ	$5C3
NG_tokenize		equ	$260
Parse2DMultiExpr		equ	$4B
is0		equ	$269
NG_approxESI		equ	$25C
push_expression		equ	$44D
is_variable		equ	$488
signum_Float		equ	$312
is_reciprocal_of_quantum		equ	$50A
is_independent_of_tail		equ	$2D7
ClearUserDef		equ	$7E
FolderDelAllTemp		equ	$75
TempFolderName		equ	$76
HSYMtoName		equ	$7A
SymFindMain		equ	$61
FolderCount		equ	$6B
SymAddMain		equ	$5D
VarRecall		equ	$85
SymCpy		equ	$82
SymCmp		equ	$81
FolderCurTemp		equ	$72
SymAdd		equ	$5C
StrToTokN		equ	$7B
GetDataType		equ	$435
SymFindPtr		equ	$283
ResetSymFlags		equ	$8E
CheckLinkLockFlag		equ	$7F
FolderOp		equ	$69
FindSymInFolder		equ	$71
SymMove		equ	$63
QSysProtected		equ	$88
SymFind		equ	$60
IsMainFolderStr		equ	$77
SymFindNext		equ	$6D
TokToStrN		equ	$7C
CheckSysFunc		equ	$89
FolderAddTemp		equ	$73
ValidateSymName		equ	$84
CheckReservedName		equ	$8B
partial_len		equ	$11C
SetOK		equ	$456
EM_twinSymFromExtMem		equ	$166
DerefSym		equ	$79
SymDel		equ	$5E
checkCurrent		equ	$121
FolderGetCur		equ	$68
FolderFind		equ	$67
SymAddTwin		equ	$27F
SymFindHome		equ	$62
SymFindFirst		equ	$6C
AddSymToFolder		equ	$70
GetFuncPrgmBodyPtr		equ	$43A
SymFindFolderName		equ	$6F
SymDelTwin		equ	$280
SymSysVar		equ	$8C
FolderAdd		equ	$64
SymFindPrev		equ	$6E
HSymDel		equ	$5F
SmapTypeStrings		equ	$436
FolderCur		equ	$65
SymCpy0		equ	$83
EX_stoBCD		equ	$C0
VarStore		equ	$86
FolderClear		equ	$66
MakeHSym		equ	$282
FolderDelTemp		equ	$74
FolderRename		equ	$6A
FolderDel		equ	$66
EM_moveSymFromExtMem		equ	$161
EM_moveSymToExtMem		equ	$162
OO_GetFirstFlashAppSectorAddress		equ	$4F3
OO_GetFlashAppSize		equ	$477
OO_GetEndOfAllFlashApps		equ	$3D2
EV_defaultHandler		equ	$157
EV_setFKeyState		equ	$D3
EV_sendEventSide		equ	$CF
MO_option		equ	$447
EV_suspendPainting		equ	$D7
EV_sendString		equ	$D0
handleVarLinkKey		equ	$129
EV_eventLoop		equ	$158
EV_centralDispatcher		equ	$156
EV_hook		equ	$2A3
EV_captureEvents		equ	$C6
EV_notifySwitchGraph		equ	$CA
EV_setCmdState		equ	$D2
EV_getc		equ	$C8
EV_sendEvent		equ	$CE
EV_restorePainting		equ	$CD
EV_paintOneWindow		equ	$CB
EV_startSide		equ	$D5
EV_setCmdCheck		equ	$D1
CAT_dialog		equ	$125
MO_sendQuit		equ	$DF
EV_startApp		equ	$D4
MO_currentOptions		equ	$D9
MO_notifyModeChange		equ	$DE
EV_startTask		equ	$D6
EV_clearPasteString		equ	$C7
TIOS_EV_getAppID		equ	$454
EV_paintWindows		equ	$CC
MO_isMultigraphTask		equ	$DC
EV_registerMenu		equ	$159
MO_digestOptions		equ	$DB
ABT_dialog		equ	$10D
MO_modeDialog		equ	$DD
handleRclKey		equ	$14F
EV_getSplitRect		equ	$C9
MO_defaults		equ	$DA
ModeSettings		equ	$447
EV_switch		equ	$D8
BN_prodMod		equ	$124
MD5Init		equ	$254
BN_power17Mod		equ	$122
MD5Done		equ	$257
MD5Update		equ	$255
BN_powerMod		equ	$123
cdecrypt		equ	$127
MD5Final		equ	$256
FSetVer		equ	$3E4
FCreate		equ	$3D6
FOpen		equ	$3DE
FSetPos		equ	$3E1
FFindNext		equ	$3DA
FClose		equ	$3D5
FAccess		equ	$3D4
FSetBufSize		equ	$3E2
FEof		equ	$3D8
FGetC		equ	$3DB
FStatus		equ	$3E5
FFindFirst		equ	$3D9
FSetSize		equ	$3E3
FDelete		equ	$3D7
FGetPos		equ	$3DC
FRead		equ	$3E0
FWrite		equ	$3E7
FType		equ	$3E6
FPutC		equ	$3DF
FGetSize		equ	$3DD
LOC_getLocalDateFormat		equ	$58F
OSContrastDn		equ	$297
OSqclear		equ	$3AD
OSTimerExpired		equ	$F3
idle		equ	$29B
OSenqueue		equ	$3A9
AB_prodid		equ	$29D
LOC_localVersionDate		equ	$591
OSTimerRestart		equ	$F4
off		equ	$29A
OSClearBreak		equ	$ED
OSqinquire		equ	$3AB
OSRegisterTimer		equ	$F0
NeedStack		equ	$A4
OSTimerCurVal		equ	$F2
ReleaseVersion		equ	$440
OSDisableBreak		equ	$EF
HelpKeys		equ	$181
CB_replaceTEXT		equ	$C1
EX_getBasecodeParmBlock		equ	$5DA
LOC_formatDate		equ	$590
OSFreeTimer		equ	$F1
OSEnableBreak		equ	$EE
XR_stringPtr		equ	$293
CU_stop		equ	$C5
QModeKey		equ	$182
EX_patch		equ	$15A
OSReset		equ	$294
OSdequeue		equ	$3AA
QSysKey		equ	$183
CU_restore		equ	$C3
ReleaseDate		equ	$43F
OSCheckBreak		equ	$EC
CU_start		equ	$C4
OSSetSR		equ	$29C
AB_prodname		equ	$29E
AB_serno		equ	$29F
AB_getGateArrayVersion		equ	$15E
CB_fetchTEXT		equ	$C2
WordInList		equ	$184
OSContrastUp		equ	$296
SumStoChkMem		equ	$295
OSOnBreak		equ	$46E
CU_cursorState		equ	$503
OSqhead		equ	$3AC
FiftyMsecTick		equ	$4FC

ScreenClear equ $19e
bcdadd equ $b6
bcdcmp equ $bb
bcddiv equ $b9
bcdbcd equ $bd
bcdmul equ $b8
bcdneg equ $ba
bcdsub equ $b7
bcdlong equ $bc

ST_showHelp		equ	$E6
DrawTo		equ	$19C
flush_link		equ	$24D
receive		equ	$24F
reset_link		equ	$24C
transmit		equ	$250
tx_free		equ	$252

SymFindFoldername  equ $6F
MakeHsym  equ $282

LCD_MEM equ $4c00
doorsos::main_lcd equ LCD_MEM
doorsos::globals equ $4c00

ROM_CALL macro
 move.l $C8,a4
 move.l \1*4(a4),a4
 jsr (a4)
 endm

ROM_CALL2 macro
 move.l $C8,a4
 move.l \1*4(a4),a4
 endm

inc	MACRO
	addq.\0	#1,\1
	ENDM
INC	MACRO
	addq.\0	#1,\1
	ENDM
dec	MACRO
	subq.\0	#1,\1
	ENDM
DEC	MACRO
	subq.\0	#1,\1
	ENDM


push	MACRO
	move.\0	\1,-(a7)
	ENDM

pop	MACRO
	move.\0	(a7)+,\1
	ENDM
pushm	MACRO
	movem.\0	\1,-(a7)
	ENDM

popm	MACRO
	movem.\0	(a7)+,\1
	ENDM

PUSH	MACRO
	move.\0	\1,-(a7)
	ENDM

POP	MACRO
	move.\0	(a7)+,\1
	ENDM
PUSHM	MACRO
	movem.\0	\1,-(a7)
	ENDM

POPM	MACRO
	movem.\0	(a7)+,\1
	ENDM

doorsos::SYM_ENTRY.name equ 0
doorsos::SYM_ENTRY.flags equ 8
doorsos::SYM_ENTRY.hVal equ $c
doorsos::NULL equ 0
doorsos::H_NULL equ 0
doorsos::RAND_MAX equ $7fff
ACTIVITY_IDLE equ 0
ACTIVITY_BUSY equ 1
ACTIVITY_PAUSED equ 2
ER_STOP equ 2
ER_DIMENSION equ 230
ER_MEMORY equ 670
ER_MEMORY_DML equ 810
UNDEFINED_TAG equ $2a
LIST_TAG equ $d9
MATRIX_TAG equ $db
END_TAG equ $e5
CALC_TI89 equ 0
CALC_TI92PLUS equ 1
_nostub
_ti89
_ti92plus
