util::find_pixel equ util@0000
util::pixel_on equ util@0001
util::pixel_off equ util@0002
util::pixel_chg equ util@0003
util::prep_rect equ util@0004
util::frame_rect equ util@0005
util::erase_rect equ util@0006
util::show_dialog equ util@0007
util::clear_dialog equ util@0008
util::clr_scr equ util@0009
util::zap_screen equ util@000A
util::idle_loop equ util@000B
util::random equ util@000C
util::DrawCharXY equ util@000D
util::exec equ util@000E
util::FindSymEntry equ util@000F
util::rand_seed equ util@0010
util::InitFargoCompatibility equ util@0011
util::DeinitFargoCompatibility equ util@0012
util::__SF_font equ util@0013 ;FargoII binary compat only

flib::find_pixel equ util::find_pixel
flib::pixel_on equ util::pixel_on
flib::pixel_off equ util::pixel_off
flib::pixel_chg equ util::pixel_chg
flib::prep_rect equ util::prep_rect
flib::frame_rect equ util::frame_rect
flib::erase_rect equ util::erase_rect
flib::show_dialog equ util::show_dialog
flib::clear_dialog equ util::clear_dialog
flib::clr_scr equ util::clr_scr
flib::zap_screen equ util::zap_screen
flib::idle_loop equ util::idle_loop
flib::random equ util::random
flib::rand_seed equ util::rand_seed
tios::DrawCharXY equ util::DrawCharXY
kernel::exec equ util::exec
tios::FindSymEntry equ util::FindSymEntry
