#!/bin/sh
#
# Install the TIGCC Tools Suite
#
echo TIGCC script: compiling and installing the 'TIGCC Tools Suite'
cd ../tt/;
./makelinux.sh
cp -Rf linuxbin/* $TIGCC/bin
rm -Rf linuxbin linuxsrc
echo Done.
