.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KTIGCC 1 "mai 11, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ktigcc \- ASM/C IDE for TIGCC
.SH SYNOPSIS
.B ktigcc
.RI [ Qt-options ] [ KDE-options ] " file"
.SH DESCRIPTION
.B ktigcc
is a full-featured IDE for TIGCC.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B file
Project to open.
.SH SEE ALSO
tigcc
.SH AUTHOR
ktigcc was written by Kevin Kofler <Kevin@tigcc.ticalc.org>.
.PP
This manual page was written by Romain Lievin <roms@tilp.info>,
for the Debian project.
