#! /bin/sh
#
# This script installs the TIGCC documentation
# For this, a directory "doc" has to be created.
#
echo TIGCC script: Installing TIGCC documentation...

mkdir $TIGCC/doc
cd ..; cp AUTHORS BUGS CHANGELOG COPYING DIRECTORIES HOWTO INSTALL README README.linux README.osX $TIGCC/doc

mkdir $TIGCC/doc/a68k
cd sources/a68k; cp Bugs.txt Doc.txt History.txt ToDo.txt $TIGCC/doc/a68k

mkdir $TIGCC/doc/tigcc
cd ../tigcc; cp AUTHORS  COPYING  ChangeLog  README $TIGCC/doc/tigcc

mkdir $TIGCC/doc/tprbuilder
cd ../tprbuilder; cp AUTHORS  COPYING  ChangeLog  README $TIGCC/doc/tprbuilder

rm -Rf $TIGCC/doc/parser

mkdir $TIGCC/doc/patcher
cd ../patcher; cp AUTHORS  COPYING  ChangeLog  README $TIGCC/doc/patcher

rm -Rf $TIGCC/doc/html
cd ../../tigcclib/doc; cp -Rf html $TIGCC/doc
rm -Rf $TIGCC/doc/tigcclib
pushd $TIGCC/doc >/dev/null
ln -sf html tigcclib
popd >/dev/null
cp ../../tigcclib/doc/converter/tigccdoc $TIGCC/bin


echo TIGCC script: Creating TIGCC projects folder...
mkdir $TIGCC/projects

echo Done.
