#! /bin/sh
#
# This script installs the TIGCCLIB.
# For this, 2 directories have to be created. One (include) contains header
# files, the other (lib) contains libraries.
#
echo TIGCC script: Installing TIGCCLIB...
rm -Rf $TIGCC/include
cp -Rf ../tigcclib/include  $TIGCC
ln -sf $TIGCC/include/asm/os.h $TIGCC/include/asm/OS.h
rm -Rf $TIGCC/lib
cp -Rf ../tigcclib/lib $TIGCC
rm -Rf $TIGCC/examples
cp -Rf ../tigcclib/examples $TIGCC

#cd ../tigcclib/src; make; make clean; cp tigcc.a $TIGCC/include/c
