#! /bin/sh
if [ -z $TIGCC ]
 then echo Install_All: error: \$TIGCC not defined; exit 1
fi
mkdir $TIGCC
if [ "x$GCC4TIHOST" != "x" ]; then
echo Compiling GCC4TI on custom host $GCC4TIHOST
export GCC4TIHOST
fi

(./Install_step_1 && ./Install_step_2 && ./Install_step_3 && ./Install_step_4 && ./Install_step_5) || exit 1;
