#!/bin/sh
#
# Install the ExePack support from the TIGCC Tools Suite
#
echo TIGCC script: Compiling and installing ExePack support...
cd ../sources/ttpack/
# check if CC is set, otherwise default to gcc
if [ -z "$CC" ]
 then CC=gcc
fi
# check if CFLAGS is set, otherwise default to '-Os -s'
if [ -z "$CFLAGS" ]
 then CFLAGS='-Os -s'
fi
$CC $CFLAGS -o $TIGCC/bin/ttpack ttpack.c
$CC $CFLAGS -o $TIGCC/bin/ttbin2oth ttbin2oth.c
echo Done.
