#! /bin/sh
#
# This script creates a tarball of the sources.
# updatesrc and updatedoc must be run prior to running this script.
#

OUTDIR=../gcc4ti-sources

echo GCC4TI script: Packaging source:
echo clamscan...
clamscan "$OUTDIR"
echo tar...
cd "$OUTDIR"
tar -c --exclude=.svn -f gcc4ti_src.tar scripts sources tigcclib AUTHORS BUGS CHANGELOG COPYING DIRECTORIES HOWTO INSTALL README README.linux;
echo bzip2...
rm -f gcc4ti_src.tar.bz2
bzip2 -9 gcc4ti_src.tar
echo Done.
