#! /bin/sh
#
# This script creates a tarball of the binaries.
# Everything must have been build prior to running this script.
#

OUTDIR=../gcc4ti-sources

echo GCC4TI script: Packaging binaries:
#echo stripping...
#strip $TIGCC/bin/*
echo clamscan...
clamscan -ir $TIGCC
echo tar...
PWDSAVE="`pwd`"
cd $TIGCC
tar -c --exclude=projects/* --exclude=bin/quill.drv --exclude=lib/quill.drv --exclude=lib/fargo.a -f "$PWDSAVE/$OUTDIR/gcc4ti_bin.tar" bin doc examples include lib projects
cd "$PWDSAVE/$OUTDIR"
echo bzip2...
rm -f gcc4ti_bin.tar.bz2
bzip2 -9 gcc4ti_bin.tar
echo Done.
