#! /bin/sh
#
# This script creates an Unix installer (self-extractible archive) using
# "makeself" ( http://megastep.org/makeself/ , package "makeself").
# Everything must have been built and installed prior to running this script.
#

if test \! -d $TIGCC ; then
   echo "Directory TIGCC=$TIGCC not found."
   exit 1
fi

MY_PWD="`dirname $0`/.."
if type makeself > /dev/null 2> /dev/null ; then
MAKESELF=makeself
elif type makeself.sh > /dev/null 2> /dev/null ; then
MAKESELF=makeself.sh
else
    echo "MAKESELF not found. Can't generate installation script. Abort."
    exit 2
fi
rm -rf /tmp/gcc4ti
cp -r $TIGCC /tmp/gcc4ti
cp $MY_PWD/scripts/setup.sh /tmp/gcc4ti
$MAKESELF --bzip2 /tmp/gcc4ti $MY_PWD/gcc4ti-install.sh "GCC4TI Install" ./setup.sh
rm -rf /tmp/gcc4ti
echo Done.
