#! /bin/sh
#
# This script rebuilds the documentation part of the tree suitable for `updatesrc` and `package_src`.
#
# NOTE: this script assumes the example configuration mentioned in
# doc/Programs/HelpSystem.ini:
#
#SystemFolder=C:\doc\System [symlink to trunk/tigcc/doc/System]
#SourceFolder=C:\doc [symlink to trunk/tigcc/doc]
#DestFolder=C:\docfiles\CHMFiles [symlink to trunk/tigcc/doc/System/CHMFiles]
#WebFolder=C:\docfiles\WebFiles [symlink to trunk/tigcc/doc/System/WebFiles]
#IncludeFolder=C:\include\C [symlink to trunk/tigcc/include/C]
#ExamplesFolder=C:\examples [symlink to trunk/tigcc/examples]
#
# The relevant contents of ~/.wine/drive_c are:
# $ ls -l ~/.wine/drive_c/
# lrwxrwxrwx  1 1000 100       22 14 sept. 10:55 doc -> gcc4ti/trunk/tigcc/doc
# lrwxrwxrwx  1 1000 100       29 14 sept. 10:57 docfiles -> gcc4ti/trunk/tigcc/doc/System
# lrwxrwxrwx  1 1000 100       27 14 sept. 10:57 examples -> gcc4ti/trunk/tigcc/examples
# lrwxrwxrwx  1 1000 100       32 14 sept. 10:55 gcc4ti -> <root of the gcc4ti repository clone>
# lrwxrwxrwx  1 1000 100       26 14 sept. 10:57 include -> gcc4ti/trunk/tigcc/include

TIGCCDIR=../../tigcc
DOCDIR=~/.wine/drive_c/docfiles/
OUTDIR=../gcc4ti-0.96b11
iswin1=`echo $GCC4TIHOST | grep -E -i "msys|mingw|cygwin"`
iswin2=`uname -a | grep -E -i "msys|mingw|cygwin"`
if [ "x$iswin1" = "x" -a "x$iswin2" = "x" ]; then
WINE=wine
else
WINE=
fi

CC=gcc


echo Generating documentation \(will take up to several minutes\)...
echo Includes
$WINE "$TIGCCDIR/doc/Programs/Update/UpdateInclude.exe"
echo Keywords
$WINE "$TIGCCDIR/doc/Programs/Update/UpdateKeywords.exe"
echo Info
$WINE "$TIGCCDIR/doc/Programs/Update/UpdateInfo.exe"
echo Index
$WINE "$TIGCCDIR/doc/Programs/Update/UpdateIndex.exe"

echo Converting CHM documentation to Qt DCF/ADP format \(will take several minutes\)...
cd "$TIGCCDIR/doc/converter"
$CC -O3 -Wall -W -o chm2dcf chm2dcf.c
cd "../System/CHMFiles"
../../converter/chm2dcf; rm ../../converter/chm2dcf
../../converter/dcf2adp
echo Done.
