#! /bin/sh
#
# This script updates the tree suitable for `package_src`
# (except the documentation: this is the duty of `updatedoc`).
#

TIGCCDIR=../../tigcc
A68KSRCDIR=../../external/a68k/source
TIGCCLINUXDIR=../../tigcc-linux
OUTDIR=../gcc4ti-sources

echo Updating source tree...
mkdir -p "$OUTDIR/tigcclib"
mkdir -p "$OUTDIR/sources"

# TIGCCLIB components
echo Updating archive \(tigcclib/src\)...
rm -rf "$OUTDIR/tigcclib/src"
cp -prf "$TIGCCDIR/archive" "$OUTDIR/tigcclib/src"
rm -Rf "$OUTDIR"/tigcclib/src/*.a

echo Updating examples...
rm -rf "$OUTDIR/tigcclib/examples"
cp -prf "$TIGCCDIR/examples" "$OUTDIR/tigcclib/examples"

echo Updating hsf2rc...
rm -rf "$OUTDIR/tigcclib/hsf2rc"
cp -prf "$TIGCCDIR/hsf2rc" "$OUTDIR/tigcclib/hsf2rc"

echo Updating include...
rm -rf "$OUTDIR/tigcclib/include"
mkdir "$OUTDIR/tigcclib/include"
cp -prf "$TIGCCDIR/include/C" "$OUTDIR/tigcclib/include/c"
cp -prf "$TIGCCDIR/include/ASM" "$OUTDIR/tigcclib/include/asm"
cp -prf "$TIGCCDIR/include/S" "$OUTDIR/tigcclib/include/s"
rm -rf "$OUTDIR/tigcclib/include/c/Completion"

echo Updating starters...
rm -rf "$OUTDIR/tigcclib/starters"
cp -prf "$TIGCCDIR/starters" "$OUTDIR/tigcclib/starters"
rm -rf "$OUTDIR/tigcclib/starters/build" "$OUTDIR/tigcclib/starters/test" \
       "$OUTDIR"/tigcclib/starters/*.89z "$OUTDIR"/tigcclib/starters/*.9xz \
       "$OUTDIR"/tigcclib/starters/*.v2z "$OUTDIR"/tigcclib/starters/*.o


# Toolchain components
echo Updating gcc \(TIGCC patches\)...
rm -rf "$OUTDIR/sources/gcc"
cp -prf "$TIGCCDIR/gcc" "$OUTDIR/sources/gcc"

echo Updating ld-tigcc...
rm -rf "$OUTDIR/sources/ld-tigcc"
cp -prf "$TIGCCDIR/ld-tigcc" "$OUTDIR/sources/ld-tigcc"
rm -f "$OUTDIR"/sources/ld-tigcc/*.o "$OUTDIR"/sources/ld-tigcc/ar/*.o \
      "$OUTDIR"/sources/ld-tigcc/ar/export/*.o "$OUTDIR"/sources/ld-tigcc/ar/import/*.o \
      "$OUTDIR"/sources/ld-tigcc/bincode/*.o  "$OUTDIR"/sources/ld-tigcc/export/*.o \
      "$OUTDIR"/sources/ld-tigcc/formats/*.o "$OUTDIR"/sources/ld-tigcc/import/*.o \
      "$OUTDIR"/sources/ld-tigcc/insert/*.o "$OUTDIR"/sources/ld-tigcc/insert/model/*.o \
      "$OUTDIR/sources/ld-tigcc/ar-tigcc" "$OUTDIR/sources/ld-tigcc/ld-tigcc" \
      "$OUTDIR/sources/ld-tigcc/link.dll"

echo Updating tprbuilder...
rm -rf "$OUTDIR/sources/tprbuilder"
cp -prf "$TIGCCDIR/tprbuilder" "$OUTDIR/sources/tprbuilder"


# Other components
echo Updating readme...
rm -f "$OUTDIR/README"
cp -pf "$TIGCCDIR/readme/Readme.txt" "$OUTDIR/README"

echo Updating TI-68k developer utilities \(formerly TIGCC Tools Suite\)...
rm -rf "$OUTDIR/sources/tools"
cp -prf "$TIGCCDIR/tools" "$OUTDIR/sources/tools"
rm -rf "$OUTDIR/sources/tools/bin"

echo Updating lib...
rm -rf "$OUTDIR/tigcclib/lib"
mkdir "$OUTDIR/tigcclib/lib"
cp -pf "$TIGCCDIR/archive/tigcc.a" "$TIGCCDIR/archive/flashos.a" \
       "$TIGCCDIR/starters/build/pstarter.o" "$OUTDIR/tigcclib/lib/"

echo Updating a68k...
rm -rf "$OUTDIR/sources/a68k"
mkdir -p "$OUTDIR/sources/a68k"
cp -pf "$A68KSRCDIR"/* "$OUTDIR/sources/a68k"

# Components in Linux/*nix
echo Updating envreg...
rm -rf "$OUTDIR/sources/envreg"
cp -prf "$TIGCCLINUXDIR/sources/envreg" "$OUTDIR/sources/envreg"

echo Updating patcher...
rm -rf "$OUTDIR/sources/patcher"
cp -prf "$TIGCCLINUXDIR/sources/patcher" "$OUTDIR/sources/patcher"
rm -f "$OUTDIR/sources/patcher/src/patcher"

echo Updating tigcc...
rm -rf "$OUTDIR/sources/tigcc"
cp -prf "$TIGCCLINUXDIR/sources/tigcc" "$OUTDIR/sources/tigcc"
rm -f "$OUTDIR/sources/tigcc/src/tigcc"

echo Updating source directory list...
cp -prf "$TIGCCLINUXDIR/sources/DIRECTORIES" "$OUTDIR/sources/"

echo Updating text documentation...
cp -prf "$TIGCCLINUXDIR/AUTHORS" "$OUTDIR/"
cp -prf "$TIGCCLINUXDIR/BUGS" "$OUTDIR/"
cp -prf "$TIGCCLINUXDIR/CHANGELOG" "$OUTDIR/"
cp -prf "$TIGCCLINUXDIR/COPYING" "$OUTDIR/"
cp -prf "$TIGCCLINUXDIR/DIRECTORIES" "$OUTDIR/"
cp -prf "$TIGCCLINUXDIR/HOWTO" "$OUTDIR/"
cp -prf "$TIGCCLINUXDIR/INSTALL" "$OUTDIR/"
cp -prf "$TIGCCLINUXDIR/README.linux" "$OUTDIR/"
cp -prf "$TIGCCLINUXDIR/README.osX" "$OUTDIR/"

echo Updating scripts...
cp -prf "$TIGCCLINUXDIR/scripts/" "$OUTDIR/"
chmod +x "$OUTDIR"/scripts/[^S]*

echo Done.
