#!/bin/sh
# DCF2ADP - converter for a QT Assistant 3.1 DCF file into a QT Assistant 3.2
#           ADP file
#
# Copyright (C) 2003-2006 Kevin Kofler
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

echo \<assistantconfig version=\"3.2.0\"\> >qt-assistant.adp
echo \<profile\> >>qt-assistant.adp
echo \<property name=\"name\"\>TIGCCDoc\</property\> >>qt-assistant.adp
echo \<property name=\"title\"\>TIGCC Documentation\</property\> >>qt-assistant.adp
#echo \<property name=\"applicationicon\"\>logo.png\</property\> >>qt-assistant.adp
echo \<property name=\"startpage\"\>index.html\</property\> >>qt-assistant.adp
#echo \<property name=\"aboutmenutext\"\>About Help\</property\> >>qt-assistant.adp
#echo \<property name=\"abouturl\"\>../about.txt\</property\> >>qt-assistant.adp
#echo \<property name=\"assistantdocs\"\>../../../doc/html\</property\> >>qt-assistant.adp
echo \</profile\> >>qt-assistant.adp
tail -n +2 qt-assistant.dcf >>qt-assistant.adp
echo \</assistantconfig\> >>qt-assistant.adp
